from enum import Enum


class ModelFamily(str, Enum):
    NAIVE = "NAIVE"
    SEASONAL_NAIVE = "SEASONAL_NAIVE"
    MOVING_AVERAGE = "MOVING_AVERAGE"
    ROBUST_MOVING_AVERAGE = "ROBUST_MOVING_AVERAGE"
    ARIMA = "ARIMA"
    SARIMA = "SARIMA"
    ETS = "ETS"
    CROSTON = "CROSTON"
    SBA = "SBA"
    TSB = "TSB"
    XGBOOST = "XGBOOST"
    RANDOM_FOREST = "RANDOM_FOREST"


class EvaluationStatus(str, Enum):
    EVALUATED = "EVALUATED"
    INELIGIBLE = "INELIGIBLE"
    MODEL_FAILED = "MODEL_FAILED"
    NOT_ASSESSED = "NOT_ASSESSED"


class ForecastStatus(str, Enum):
    AVAILABLE = "FORECAST_AVAILABLE"
    LIMITED = "FORECAST_LIMITED"
    NO_VALID_MODEL = "NO_VALID_MODEL"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    NO_DEMAND_SIGNAL = "NO_DEMAND_SIGNAL"
