"""Initial AURIX enterprise schema baseline.

Revision ID: 0001_initial_aurix_schema
Revises:
Create Date: 2026-08-15

This baseline represents the complete current SQLAlchemy ORM schema and
includes the persistent AI quota reservation layer introduced during the
final backend hardening pass.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial_aurix_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ai_audit_logs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('conversation_id', sa.String(length=64), nullable=True),
        sa.Column('query_type', sa.String(length=32), nullable=False),
        sa.Column('provider_name', sa.String(length=64), nullable=False),
        sa.Column('model_name', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('grounding_status', sa.String(length=32), nullable=False),
        sa.Column('routing_meta_json', sa.Text(), nullable=True),
        sa.Column('token_usage_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_ai_audit_tenant', 'ai_audit_logs', ['tenant_id', 'id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_conversation_id'), 'ai_audit_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_id'), 'ai_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_tenant_id'), 'ai_audit_logs', ['tenant_id'], unique=False)

    op.create_table(
        'ai_usage_policies',
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('monthly_spend_limit_usd', sa.Float(), nullable=False),
        sa.Column('daily_spend_limit_usd', sa.Float(), nullable=False),
        sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
        sa.Column('daily_token_limit', sa.Integer(), nullable=False),
        sa.Column('monthly_request_limit', sa.Integer(), nullable=False),
        sa.Column('daily_request_limit', sa.Integer(), nullable=False),
        sa.Column('warning_threshold_pct', sa.Float(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('reserved_spend_usd', sa.Float(), nullable=False),
        sa.Column('reserved_token_count', sa.Integer(), nullable=False),
        sa.Column('reserved_request_count', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('tenant_id'),
    )
    op.create_index(op.f('ix_ai_usage_policies_tenant_id'), 'ai_usage_policies', ['tenant_id'], unique=False)

    op.create_table(
        'ai_usage_ledgers',
        sa.Column('record_id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('date_str', sa.String(length=10), nullable=False),
        sa.Column('month_str', sa.String(length=7), nullable=False),
        sa.Column('provider', sa.String(length=64), nullable=False),
        sa.Column('model', sa.String(length=128), nullable=False),
        sa.Column('input_tokens', sa.Integer(), nullable=False),
        sa.Column('output_tokens', sa.Integer(), nullable=False),
        sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
        sa.Column('is_fallback', sa.Boolean(), nullable=False),
        sa.Column('reservation_id', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('record_id'),
    )
    op.create_index('ix_ai_ledger_tenant_date', 'ai_usage_ledgers', ['tenant_id', 'date_str'], unique=False)
    op.create_index('ix_ai_ledger_tenant_month', 'ai_usage_ledgers', ['tenant_id', 'month_str'], unique=False)
    op.create_index(op.f('ix_ai_usage_ledgers_date_str'), 'ai_usage_ledgers', ['date_str'], unique=False)
    op.create_index(op.f('ix_ai_usage_ledgers_month_str'), 'ai_usage_ledgers', ['month_str'], unique=False)
    op.create_index(op.f('ix_ai_usage_ledgers_tenant_id'), 'ai_usage_ledgers', ['tenant_id'], unique=False)
    op.create_index('ix_ai_ledger_tenant_reservation', 'ai_usage_ledgers', ['tenant_id', 'reservation_id'], unique=False)

    op.create_table(
        'ai_quota_reservations',
        sa.Column('reservation_id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('provider', sa.String(length=64), nullable=False),
        sa.Column('model', sa.String(length=128), nullable=False),
        sa.Column('estimated_input_tokens', sa.Integer(), nullable=False),
        sa.Column('estimated_output_tokens', sa.Integer(), nullable=False),
        sa.Column('estimated_token_count', sa.Integer(), nullable=False),
        sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
        sa.Column('estimated_request_count', sa.Integer(), nullable=False),
        sa.Column('actual_input_tokens', sa.Integer(), nullable=True),
        sa.Column('actual_output_tokens', sa.Integer(), nullable=True),
        sa.Column('actual_token_count', sa.Integer(), nullable=True),
        sa.Column('actual_cost_usd', sa.Float(), nullable=True),
        sa.Column('actual_request_count', sa.Integer(), nullable=True),
        sa.Column('ledger_record_id', sa.String(length=64), nullable=True),
        sa.Column('release_reason', sa.String(length=255), nullable=True),
        sa.Column('error_message', sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint('reservation_id'),
    )
    op.create_index('ix_ai_reservation_tenant_status', 'ai_quota_reservations', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_ai_reservation_tenant_created', 'ai_quota_reservations', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_ai_reservation_tenant_expires', 'ai_quota_reservations', ['tenant_id', 'expires_at'], unique=False)
    op.create_index('ix_ai_reservation_tenant_ledger', 'ai_quota_reservations', ['tenant_id', 'ledger_record_id'], unique=False)
    op.create_index('ix_ai_quota_reservations_ledger_record_id', 'ai_quota_reservations', ['ledger_record_id'], unique=False)

    op.create_table(
        'business_signals',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('signal_type', sa.String(length=64), nullable=False),
        sa.Column('severity', sa.String(length=32), nullable=False),
        sa.Column('domain', sa.String(length=32), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('evidence_json', sa.Text(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_signal_tenant_run', 'business_signals', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_business_signals_id'), 'business_signals', ['id'], unique=False)
    op.create_index(op.f('ix_business_signals_run_id'), 'business_signals', ['run_id'], unique=False)
    op.create_index(op.f('ix_business_signals_signal_type'), 'business_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_business_signals_tenant_id'), 'business_signals', ['tenant_id'], unique=False)

    op.create_table(
        'capability_states',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('capability_name', sa.String(length=64), nullable=False),
        sa.Column('domain', sa.String(length=32), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('freshness_state', sa.String(length=32), nullable=False),
        sa.Column('readiness_json', sa.Text(), nullable=True),
        sa.Column('missing_prerequisites_json', sa.Text(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_cap_state_tenant_name', 'capability_states', ['tenant_id', 'capability_name'], unique=False)
    op.create_index('idx_cap_state_tenant_run', 'capability_states', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_capability_states_capability_name'), 'capability_states', ['capability_name'], unique=False)
    op.create_index(op.f('ix_capability_states_id'), 'capability_states', ['id'], unique=False)
    op.create_index(op.f('ix_capability_states_run_id'), 'capability_states', ['run_id'], unique=False)
    op.create_index(op.f('ix_capability_states_tenant_id'), 'capability_states', ['tenant_id'], unique=False)

    op.create_table(
        'conversation_messages',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('conversation_id', sa.String(length=64), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('provenance_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_msg_tenant_conv', 'conversation_messages', ['tenant_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_tenant_id'), 'conversation_messages', ['tenant_id'], unique=False)

    op.create_table(
        'conversations',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('title', sa.String(length=256), nullable=True),
        sa.Column('active_domain', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_conversation_tenant', 'conversations', ['tenant_id', 'id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)

    op.create_table(
        'executive_summaries',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('headline', sa.Text(), nullable=False),
        sa.Column('narrative_json', sa.Text(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_summary_tenant_run', 'executive_summaries', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_executive_summaries_id'), 'executive_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_executive_summaries_run_id'), 'executive_summaries', ['run_id'], unique=False)
    op.create_index(op.f('ix_executive_summaries_tenant_id'), 'executive_summaries', ['tenant_id'], unique=False)

    op.create_table(
        'financial_baseline_snapshots',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('currency', sa.String(length=16), nullable=False),
        sa.Column('baseline_metrics_json', sa.Text(), nullable=True),
        sa.Column('value_state', sa.String(length=32), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_fin_baseline_tenant_run', 'financial_baseline_snapshots', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_financial_baseline_snapshots_id'), 'financial_baseline_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_financial_baseline_snapshots_run_id'), 'financial_baseline_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_financial_baseline_snapshots_tenant_id'), 'financial_baseline_snapshots', ['tenant_id'], unique=False)

    op.create_table(
        'financial_intelligence_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('dataset_hash', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('configuration', sa.Text(), nullable=True),
        sa.Column('provenance', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_fin_run_tenant_hash', 'financial_intelligence_runs', ['tenant_id', 'dataset_hash'], unique=False)
    op.create_index(op.f('ix_financial_intelligence_runs_dataset_hash'), 'financial_intelligence_runs', ['dataset_hash'], unique=False)
    op.create_index(op.f('ix_financial_intelligence_runs_id'), 'financial_intelligence_runs', ['id'], unique=False)
    op.create_index(op.f('ix_financial_intelligence_runs_tenant_id'), 'financial_intelligence_runs', ['tenant_id'], unique=False)

    op.create_table(
        'forecast_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('dataset_hash', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('frequency', sa.String(length=16), nullable=False),
        sa.Column('horizon', sa.Integer(), nullable=False),
        sa.Column('configuration', sa.String(), nullable=True),
        sa.Column('provenance', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_forecast_runs_dataset_hash'), 'forecast_runs', ['dataset_hash'], unique=False)
    op.create_index(op.f('ix_forecast_runs_id'), 'forecast_runs', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_runs_tenant_id'), 'forecast_runs', ['tenant_id'], unique=False)

    op.create_table(
        'ingestion_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('source_name', sa.String(length=255), nullable=False),
        sa.Column('domain', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('data_hash', sa.String(length=128), nullable=False),
        sa.Column('record_count', sa.Integer(), nullable=False),
        sa.Column('error_count', sa.Integer(), nullable=False),
        sa.Column('validation_summary', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_ingestion_runs_data_hash'), 'ingestion_runs', ['data_hash'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_domain'), 'ingestion_runs', ['domain'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_tenant_id'), 'ingestion_runs', ['tenant_id'], unique=False)

    op.create_table(
        'intelligence_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('dataset_hash', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('configuration', sa.Text(), nullable=True),
        sa.Column('provenance', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_intel_run_tenant_hash', 'intelligence_runs', ['tenant_id', 'dataset_hash'], unique=False)
    op.create_index(op.f('ix_intelligence_runs_dataset_hash'), 'intelligence_runs', ['dataset_hash'], unique=False)
    op.create_index(op.f('ix_intelligence_runs_id'), 'intelligence_runs', ['id'], unique=False)
    op.create_index(op.f('ix_intelligence_runs_tenant_id'), 'intelligence_runs', ['tenant_id'], unique=False)

    op.create_table(
        'intelligence_snapshots',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('snapshot_json', sa.Text(), nullable=False),
        sa.Column('summary_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_snapshot_tenant_run', 'intelligence_snapshots', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_intelligence_snapshots_id'), 'intelligence_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_intelligence_snapshots_run_id'), 'intelligence_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_intelligence_snapshots_tenant_id'), 'intelligence_snapshots', ['tenant_id'], unique=False)

    op.create_table(
        'inventory_intelligence_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('forecast_run_id', sa.String(length=64), nullable=True),
        sa.Column('dataset_hash', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('configuration', sa.String(), nullable=True),
        sa.Column('provenance', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_inventory_intelligence_runs_dataset_hash'), 'inventory_intelligence_runs', ['dataset_hash'], unique=False)
    op.create_index(op.f('ix_inventory_intelligence_runs_forecast_run_id'), 'inventory_intelligence_runs', ['forecast_run_id'], unique=False)
    op.create_index(op.f('ix_inventory_intelligence_runs_id'), 'inventory_intelligence_runs', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_intelligence_runs_tenant_id'), 'inventory_intelligence_runs', ['tenant_id'], unique=False)

    op.create_table(
        'locations',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('location_name', sa.String(length=255), nullable=False),
        sa.Column('location_type', sa.String(length=64), nullable=False),
        sa.Column('country', sa.String(length=64), nullable=True),
        sa.Column('ingestion_run_id', sa.String(length=64), nullable=True),
        sa.Column('source_record_id', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_ingestion_run_id'), 'locations', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)

    op.create_table(
        'logistics_intelligence_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('dataset_hash', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('configuration', sa.String(), nullable=True),
        sa.Column('provenance', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_logistics_intelligence_runs_dataset_hash'), 'logistics_intelligence_runs', ['dataset_hash'], unique=False)
    op.create_index(op.f('ix_logistics_intelligence_runs_id'), 'logistics_intelligence_runs', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_intelligence_runs_tenant_id'), 'logistics_intelligence_runs', ['tenant_id'], unique=False)

    op.create_table(
        'network_flow_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('dataset_hash', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('node_count', sa.Integer(), nullable=False),
        sa.Column('edge_count', sa.Integer(), nullable=False),
        sa.Column('risk_count', sa.Integer(), nullable=False),
        sa.Column('duration_ms', sa.Float(), nullable=False),
        sa.Column('configuration', sa.Text(), nullable=True),
        sa.Column('provenance', sa.Text(), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_network_flow_runs_dataset_hash'), 'network_flow_runs', ['dataset_hash'], unique=False)
    op.create_index(op.f('ix_network_flow_runs_run_id'), 'network_flow_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_network_flow_runs_tenant_id'), 'network_flow_runs', ['tenant_id'], unique=False)

    op.create_table(
        'persistent_alerts',
        sa.Column('alert_id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('event_id', sa.String(length=64), nullable=False),
        sa.Column('severity', sa.String(length=32), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('deduplication_key', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('alert_id'),
    )
    op.create_index(op.f('ix_persistent_alerts_deduplication_key'), 'persistent_alerts', ['deduplication_key'], unique=False)
    op.create_index(op.f('ix_persistent_alerts_event_id'), 'persistent_alerts', ['event_id'], unique=False)
    op.create_index('ix_persistent_alerts_tenant_dedup', 'persistent_alerts', ['tenant_id', 'deduplication_key'], unique=False)
    op.create_index(op.f('ix_persistent_alerts_tenant_id'), 'persistent_alerts', ['tenant_id'], unique=False)

    op.create_table(
        'persistent_events',
        sa.Column('event_id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('idempotency_key', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('event_id'),
    )
    op.create_index(op.f('ix_persistent_events_idempotency_key'), 'persistent_events', ['idempotency_key'], unique=False)
    op.create_index('ix_persistent_events_tenant_idem', 'persistent_events', ['tenant_id', 'idempotency_key'], unique=False)
    op.create_index(op.f('ix_persistent_events_tenant_id'), 'persistent_events', ['tenant_id'], unique=False)

    op.create_table(
        'persistent_quarantine',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('event_id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('source_system', sa.String(length=64), nullable=True),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('payload_json', sa.Text(), nullable=False),
        sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_persistent_quarantine_event_id'), 'persistent_quarantine', ['event_id'], unique=False)
    op.create_index(op.f('ix_persistent_quarantine_tenant_id'), 'persistent_quarantine', ['tenant_id'], unique=False)

    op.create_table(
        'prioritized_actions',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('action_type', sa.String(length=64), nullable=False),
        sa.Column('priority_score', sa.String(length=32), nullable=False),
        sa.Column('urgency', sa.String(length=32), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('financial_exposure_json', sa.Text(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_action_tenant_run', 'prioritized_actions', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_prioritized_actions_id'), 'prioritized_actions', ['id'], unique=False)
    op.create_index(op.f('ix_prioritized_actions_run_id'), 'prioritized_actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_prioritized_actions_tenant_id'), 'prioritized_actions', ['tenant_id'], unique=False)

    op.create_table(
        'products',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('sku_code', sa.String(length=128), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('category', sa.String(length=128), nullable=True),
        sa.Column('unit_cost', sa.Float(), nullable=True),
        sa.Column('ingestion_run_id', sa.String(length=64), nullable=True),
        sa.Column('source_record_id', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_ingestion_run_id'), 'products', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_products_sku_code'), 'products', ['sku_code'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)

    op.create_table(
        'scenario_metric_snapshots',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('scenario_run_id', sa.String(length=64), nullable=False),
        sa.Column('currency', sa.String(length=16), nullable=False),
        sa.Column('scenario_metrics_json', sa.Text(), nullable=True),
        sa.Column('deltas_json', sa.Text(), nullable=True),
        sa.Column('gate_status', sa.String(length=32), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_scenario_metric_tenant_run', 'scenario_metric_snapshots', ['tenant_id', 'scenario_run_id'], unique=False)
    op.create_index(op.f('ix_scenario_metric_snapshots_id'), 'scenario_metric_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_metric_snapshots_scenario_run_id'), 'scenario_metric_snapshots', ['scenario_run_id'], unique=False)
    op.create_index(op.f('ix_scenario_metric_snapshots_tenant_id'), 'scenario_metric_snapshots', ['tenant_id'], unique=False)

    op.create_table(
        'scenario_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('scenario_id', sa.String(length=128), nullable=False),
        sa.Column('scenario_type', sa.String(length=64), nullable=False),
        sa.Column('scenario_description', sa.Text(), nullable=True),
        sa.Column('parameters_json', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_scenario_tenant_run', 'scenario_runs', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_id'), 'scenario_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_run_id'), 'scenario_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_scenario_id'), 'scenario_runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_tenant_id'), 'scenario_runs', ['tenant_id'], unique=False)

    op.create_table(
        'suppliers',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('supplier_name', sa.String(length=255), nullable=False),
        sa.Column('country', sa.String(length=64), nullable=True),
        sa.Column('lead_time_days', sa.Float(), nullable=True),
        sa.Column('ingestion_run_id', sa.String(length=64), nullable=True),
        sa.Column('source_record_id', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_ingestion_run_id'), 'suppliers', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)

    op.create_table(
        'supply_intelligence_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('dataset_hash', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('configuration', sa.String(), nullable=True),
        sa.Column('provenance', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_supply_intelligence_runs_dataset_hash'), 'supply_intelligence_runs', ['dataset_hash'], unique=False)
    op.create_index(op.f('ix_supply_intelligence_runs_id'), 'supply_intelligence_runs', ['id'], unique=False)
    op.create_index(op.f('ix_supply_intelligence_runs_tenant_id'), 'supply_intelligence_runs', ['tenant_id'], unique=False)

    op.create_table(
        'carrier_performance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('carrier_id', sa.String(length=64), nullable=False),
        sa.Column('evaluated_order_count', sa.Integer(), nullable=False),
        sa.Column('otd_rate', sa.Float(), nullable=True),
        sa.Column('in_full_rate', sa.Float(), nullable=True),
        sa.Column('otif_rate', sa.Float(), nullable=True),
        sa.Column('mean_transit_days', sa.Float(), nullable=True),
        sa.Column('transit_std_days', sa.Float(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('risk_level', sa.String(length=64), nullable=True),
        sa.Column('risk_drivers', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.ForeignKeyConstraint(['run_id'], ['logistics_intelligence_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_carrier_performance_carrier_id'), 'carrier_performance', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_performance_run_id'), 'carrier_performance', ['run_id'], unique=False)
    op.create_index(op.f('ix_carrier_performance_tenant_id'), 'carrier_performance', ['tenant_id'], unique=False)

    op.create_table(
        'forecast_points',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('forecast_run_id', sa.String(length=64), nullable=False),
        sa.Column('sku_id', sa.String(length=64), nullable=False),
        sa.Column('location_id', sa.String(length=64), nullable=True),
        sa.Column('target_date', sa.DateTime(), nullable=False),
        sa.Column('horizon_step', sa.Integer(), nullable=False),
        sa.Column('point_forecast', sa.Float(), nullable=False),
        sa.Column('raw_model_forecast', sa.Float(), nullable=False),
        sa.Column('lower_bound', sa.Float(), nullable=True),
        sa.Column('upper_bound', sa.Float(), nullable=True),
        sa.Column('model_id', sa.String(length=64), nullable=False),
        sa.Column('value_state', sa.String(length=32), nullable=False),
        sa.Column('constraint_applied', sa.Boolean(), nullable=False),
        sa.Column('constraint_reason', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_forecast_points_forecast_run_id'), 'forecast_points', ['forecast_run_id'], unique=False)
    op.create_index(op.f('ix_forecast_points_location_id'), 'forecast_points', ['location_id'], unique=False)
    op.create_index(op.f('ix_forecast_points_sku_id'), 'forecast_points', ['sku_id'], unique=False)
    op.create_index(op.f('ix_forecast_points_target_date'), 'forecast_points', ['target_date'], unique=False)
    op.create_index(op.f('ix_forecast_points_tenant_id'), 'forecast_points', ['tenant_id'], unique=False)

    op.create_table(
        'inventory_positions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sku_id', sa.String(length=64), nullable=False),
        sa.Column('location_id', sa.String(length=64), nullable=False),
        sa.Column('on_hand', sa.Float(), nullable=False),
        sa.Column('on_order', sa.Float(), nullable=False),
        sa.Column('safety_stock', sa.Float(), nullable=True),
        sa.Column('ingestion_run_id', sa.String(length=64), nullable=True),
        sa.Column('source_record_id', sa.String(length=128), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.ForeignKeyConstraint(['location_id'], ['locations.id']),
        sa.ForeignKeyConstraint(['sku_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_inventory_positions_ingestion_run_id'), 'inventory_positions', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_inventory_positions_location_id'), 'inventory_positions', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_positions_sku_id'), 'inventory_positions', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_positions_tenant_id'), 'inventory_positions', ['tenant_id'], unique=False)

    op.create_table(
        'lane_performance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('origin_id', sa.String(length=64), nullable=False),
        sa.Column('destination_id', sa.String(length=64), nullable=False),
        sa.Column('carrier_id', sa.String(length=64), nullable=True),
        sa.Column('evaluated_shipment_count', sa.Integer(), nullable=False),
        sa.Column('mean_transit_days', sa.Float(), nullable=True),
        sa.Column('median_transit_days', sa.Float(), nullable=True),
        sa.Column('p90_transit_days', sa.Float(), nullable=True),
        sa.Column('p95_transit_days', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.ForeignKeyConstraint(['run_id'], ['logistics_intelligence_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_lane_performance_carrier_id'), 'lane_performance', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_lane_performance_destination_id'), 'lane_performance', ['destination_id'], unique=False)
    op.create_index(op.f('ix_lane_performance_origin_id'), 'lane_performance', ['origin_id'], unique=False)
    op.create_index(op.f('ix_lane_performance_run_id'), 'lane_performance', ['run_id'], unique=False)
    op.create_index(op.f('ix_lane_performance_tenant_id'), 'lane_performance', ['tenant_id'], unique=False)

    op.create_table(
        'network_edge_snapshots',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('edge_id', sa.String(length=64), nullable=False),
        sa.Column('sku_id', sa.String(length=64), nullable=False),
        sa.Column('source_node_id', sa.String(length=64), nullable=False),
        sa.Column('destination_node_id', sa.String(length=64), nullable=False),
        sa.Column('transport_mode', sa.String(length=32), nullable=True),
        sa.Column('nominal_lead_time_days', sa.Float(), nullable=True),
        sa.Column('unit_transport_cost', sa.Float(), nullable=True),
        sa.Column('capacity', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('attributes_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['network_flow_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_net_edge_tenant_run', 'network_edge_snapshots', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_network_edge_snapshots_destination_node_id'), 'network_edge_snapshots', ['destination_node_id'], unique=False)
    op.create_index(op.f('ix_network_edge_snapshots_edge_id'), 'network_edge_snapshots', ['edge_id'], unique=False)
    op.create_index(op.f('ix_network_edge_snapshots_id'), 'network_edge_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_network_edge_snapshots_run_id'), 'network_edge_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_network_edge_snapshots_sku_id'), 'network_edge_snapshots', ['sku_id'], unique=False)
    op.create_index(op.f('ix_network_edge_snapshots_source_node_id'), 'network_edge_snapshots', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_network_edge_snapshots_tenant_id'), 'network_edge_snapshots', ['tenant_id'], unique=False)

    op.create_table(
        'network_node_snapshots',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('node_id', sa.String(length=64), nullable=False),
        sa.Column('node_name', sa.String(length=128), nullable=False),
        sa.Column('node_type', sa.String(length=32), nullable=False),
        sa.Column('location_name', sa.String(length=128), nullable=True),
        sa.Column('tier_level', sa.Integer(), nullable=True),
        sa.Column('holding_cost_rate', sa.Float(), nullable=True),
        sa.Column('capacity', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('attributes_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['network_flow_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_net_node_tenant_run', 'network_node_snapshots', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_network_node_snapshots_id'), 'network_node_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_network_node_snapshots_node_id'), 'network_node_snapshots', ['node_id'], unique=False)
    op.create_index(op.f('ix_network_node_snapshots_run_id'), 'network_node_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_network_node_snapshots_tenant_id'), 'network_node_snapshots', ['tenant_id'], unique=False)

    op.create_table(
        'network_optimization_runs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('objective_value', sa.Float(), nullable=True),
        sa.Column('results_json', sa.Text(), nullable=True),
        sa.Column('provenance', sa.Text(), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['network_flow_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_network_optimization_runs_run_id'), 'network_optimization_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_network_optimization_runs_tenant_id'), 'network_optimization_runs', ['tenant_id'], unique=False)

    op.create_table(
        'network_risk_snapshots',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('risk_id', sa.String(length=64), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('node_id', sa.String(length=64), nullable=True),
        sa.Column('disruption_probability', sa.Float(), nullable=True),
        sa.Column('bottleneck_severity', sa.String(length=32), nullable=True),
        sa.Column('estimated_days_to_recover', sa.Float(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('mitigation_strategy', sa.Text(), nullable=True),
        sa.Column('evidence_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['network_flow_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_network_risk_snapshots_id'), 'network_risk_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_network_risk_snapshots_node_id'), 'network_risk_snapshots', ['node_id'], unique=False)
    op.create_index(op.f('ix_network_risk_snapshots_risk_id'), 'network_risk_snapshots', ['risk_id'], unique=False)
    op.create_index(op.f('ix_network_risk_snapshots_run_id'), 'network_risk_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_network_risk_snapshots_tenant_id'), 'network_risk_snapshots', ['tenant_id'], unique=False)

    op.create_table(
        'replenishment_policies',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('sku_id', sa.String(length=64), nullable=False),
        sa.Column('location_id', sa.String(length=64), nullable=True),
        sa.Column('expected_daily_demand', sa.Float(), nullable=True),
        sa.Column('lead_time_days', sa.Float(), nullable=True),
        sa.Column('safety_stock', sa.Float(), nullable=True),
        sa.Column('reorder_point', sa.Float(), nullable=True),
        sa.Column('eoq', sa.Float(), nullable=True),
        sa.Column('reorder_triggered', sa.Boolean(), nullable=False),
        sa.Column('reorder_reason', sa.String(length=128), nullable=True),
        sa.Column('raw_order_quantity', sa.Float(), nullable=True),
        sa.Column('constrained_order_quantity', sa.Float(), nullable=True),
        sa.Column('constraint_applied', sa.Boolean(), nullable=False),
        sa.Column('constraint_reason', sa.String(length=128), nullable=True),
        sa.Column('risk_status', sa.String(length=64), nullable=True),
        sa.Column('holding_cost_exposure', sa.Float(), nullable=True),
        sa.Column('value_state', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.ForeignKeyConstraint(['run_id'], ['inventory_intelligence_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_replenishment_policies_location_id'), 'replenishment_policies', ['location_id'], unique=False)
    op.create_index(op.f('ix_replenishment_policies_run_id'), 'replenishment_policies', ['run_id'], unique=False)
    op.create_index(op.f('ix_replenishment_policies_sku_id'), 'replenishment_policies', ['sku_id'], unique=False)
    op.create_index(op.f('ix_replenishment_policies_tenant_id'), 'replenishment_policies', ['tenant_id'], unique=False)

    op.create_table(
        'shipment_evaluations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('shipment_id', sa.String(length=64), nullable=False),
        sa.Column('order_id', sa.String(length=64), nullable=True),
        sa.Column('sku_id', sa.String(length=64), nullable=True),
        sa.Column('carrier_id', sa.String(length=64), nullable=True),
        sa.Column('origin_id', sa.String(length=64), nullable=True),
        sa.Column('destination_id', sa.String(length=64), nullable=True),
        sa.Column('quantity', sa.Float(), nullable=True),
        sa.Column('weight_kg', sa.Float(), nullable=True),
        sa.Column('dispatch_date', sa.DateTime(), nullable=True),
        sa.Column('promised_delivery_date', sa.DateTime(), nullable=True),
        sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True),
        sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
        sa.Column('eta_source', sa.String(length=64), nullable=True),
        sa.Column('delay_hours', sa.Float(), nullable=True),
        sa.Column('is_delayed', sa.Boolean(), nullable=False),
        sa.Column('logistics_risk_score', sa.Float(), nullable=True),
        sa.Column('risk_level', sa.String(length=64), nullable=True),
        sa.Column('expedite_recommendation', sa.String(length=64), nullable=True),
        sa.Column('recommendation_reason', sa.String(), nullable=True),
        sa.Column('freight_cost', sa.Float(), nullable=True),
        sa.Column('cost_per_unit', sa.Float(), nullable=True),
        sa.Column('cost_per_kg', sa.Float(), nullable=True),
        sa.Column('currency', sa.String(length=16), nullable=True),
        sa.Column('value_state', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.ForeignKeyConstraint(['run_id'], ['logistics_intelligence_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_shipment_evaluations_carrier_id'), 'shipment_evaluations', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_shipment_evaluations_order_id'), 'shipment_evaluations', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipment_evaluations_run_id'), 'shipment_evaluations', ['run_id'], unique=False)
    op.create_index(op.f('ix_shipment_evaluations_shipment_id'), 'shipment_evaluations', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_evaluations_sku_id'), 'shipment_evaluations', ['sku_id'], unique=False)
    op.create_index(op.f('ix_shipment_evaluations_tenant_id'), 'shipment_evaluations', ['tenant_id'], unique=False)

    op.create_table(
        'supplier_performance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('supplier_id', sa.String(length=64), nullable=False),
        sa.Column('evaluated_order_count', sa.Integer(), nullable=False),
        sa.Column('otd_rate', sa.Float(), nullable=True),
        sa.Column('in_full_rate', sa.Float(), nullable=True),
        sa.Column('otif_rate', sa.Float(), nullable=True),
        sa.Column('fill_rate', sa.Float(), nullable=True),
        sa.Column('lead_time_mean', sa.Float(), nullable=True),
        sa.Column('lead_time_std', sa.Float(), nullable=True),
        sa.Column('defect_rate', sa.Float(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('risk_level', sa.String(length=64), nullable=True),
        sa.Column('risk_drivers', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.ForeignKeyConstraint(['run_id'], ['supply_intelligence_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_supplier_performance_run_id'), 'supplier_performance', ['run_id'], unique=False)
    op.create_index(op.f('ix_supplier_performance_supplier_id'), 'supplier_performance', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_performance_tenant_id'), 'supplier_performance', ['tenant_id'], unique=False)

    op.create_table(
        'replenishment_recommendations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('replenishment_policy_id', sa.Integer(), nullable=True),
        sa.Column('sku_id', sa.String(length=64), nullable=False),
        sa.Column('supplier_id', sa.String(length=64), nullable=False),
        sa.Column('raw_quantity', sa.Float(), nullable=False),
        sa.Column('constrained_quantity', sa.Float(), nullable=False),
        sa.Column('moq_applied', sa.Boolean(), nullable=False),
        sa.Column('pack_size_applied', sa.Boolean(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=True),
        sa.Column('total_purchase_cost', sa.Float(), nullable=True),
        sa.Column('currency', sa.String(length=16), nullable=True),
        sa.Column('selection_rank', sa.Integer(), nullable=False),
        sa.Column('selection_reason', sa.String(), nullable=True),
        sa.Column('single_source_dependency', sa.Boolean(), nullable=False),
        sa.Column('value_state', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='Logical tenant identifier ensuring strict data boundary isolation.'),
        sa.ForeignKeyConstraint(['replenishment_policy_id'], ['replenishment_policies.id']),
        sa.ForeignKeyConstraint(['run_id'], ['supply_intelligence_runs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_replenishment_recommendations_replenishment_policy_id'), 'replenishment_recommendations', ['replenishment_policy_id'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_run_id'), 'replenishment_recommendations', ['run_id'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_sku_id'), 'replenishment_recommendations', ['sku_id'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_supplier_id'), 'replenishment_recommendations', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_tenant_id'), 'replenishment_recommendations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the baseline schema in exact reverse creation order with strict foreign key safety."""

    # 40. replenishment_recommendations
    op.drop_index(op.f('ix_replenishment_recommendations_tenant_id'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_supplier_id'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_sku_id'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_run_id'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_replenishment_policy_id'), table_name='replenishment_recommendations')
    op.drop_table('replenishment_recommendations')

    # 39. supplier_performance
    op.drop_index(op.f('ix_supplier_performance_tenant_id'), table_name='supplier_performance')
    op.drop_index(op.f('ix_supplier_performance_supplier_id'), table_name='supplier_performance')
    op.drop_index(op.f('ix_supplier_performance_run_id'), table_name='supplier_performance')
    op.drop_table('supplier_performance')

    # 38. shipment_evaluations
    op.drop_index(op.f('ix_shipment_evaluations_tenant_id'), table_name='shipment_evaluations')
    op.drop_index(op.f('ix_shipment_evaluations_sku_id'), table_name='shipment_evaluations')
    op.drop_index(op.f('ix_shipment_evaluations_shipment_id'), table_name='shipment_evaluations')
    op.drop_index(op.f('ix_shipment_evaluations_run_id'), table_name='shipment_evaluations')
    op.drop_index(op.f('ix_shipment_evaluations_order_id'), table_name='shipment_evaluations')
    op.drop_index(op.f('ix_shipment_evaluations_carrier_id'), table_name='shipment_evaluations')
    op.drop_table('shipment_evaluations')

    # 37. replenishment_policies
    op.drop_index(op.f('ix_replenishment_policies_tenant_id'), table_name='replenishment_policies')
    op.drop_index(op.f('ix_replenishment_policies_sku_id'), table_name='replenishment_policies')
    op.drop_index(op.f('ix_replenishment_policies_run_id'), table_name='replenishment_policies')
    op.drop_index(op.f('ix_replenishment_policies_location_id'), table_name='replenishment_policies')
    op.drop_table('replenishment_policies')

    # 36. network_risk_snapshots
    op.drop_index(op.f('ix_network_risk_snapshots_node_id'), table_name='network_risk_snapshots')
    op.drop_index(op.f('ix_network_risk_snapshots_run_id'), table_name='network_risk_snapshots')
    op.drop_index(op.f('ix_network_risk_snapshots_risk_id'), table_name='network_risk_snapshots')
    op.drop_index(op.f('ix_network_risk_snapshots_tenant_id'), table_name='network_risk_snapshots')
    op.drop_index(op.f('ix_network_risk_snapshots_id'), table_name='network_risk_snapshots')
    op.drop_table('network_risk_snapshots')

    # 35. network_optimization_runs
    op.drop_index(op.f('ix_network_optimization_runs_tenant_id'), table_name='network_optimization_runs')
    op.drop_index(op.f('ix_network_optimization_runs_run_id'), table_name='network_optimization_runs')
    op.drop_table('network_optimization_runs')

    # 34. network_node_snapshots
    op.drop_index(op.f('ix_network_node_snapshots_tenant_id'), table_name='network_node_snapshots')
    op.drop_index(op.f('ix_network_node_snapshots_run_id'), table_name='network_node_snapshots')
    op.drop_index(op.f('ix_network_node_snapshots_node_id'), table_name='network_node_snapshots')
    op.drop_index(op.f('ix_network_node_snapshots_id'), table_name='network_node_snapshots')
    op.drop_index('idx_net_node_tenant_run', table_name='network_node_snapshots')
    op.drop_table('network_node_snapshots')

    # 33. network_edge_snapshots
    op.drop_index(op.f('ix_network_edge_snapshots_tenant_id'), table_name='network_edge_snapshots')
    op.drop_index(op.f('ix_network_edge_snapshots_source_node_id'), table_name='network_edge_snapshots')
    op.drop_index(op.f('ix_network_edge_snapshots_sku_id'), table_name='network_edge_snapshots')
    op.drop_index(op.f('ix_network_edge_snapshots_run_id'), table_name='network_edge_snapshots')
    op.drop_index(op.f('ix_network_edge_snapshots_id'), table_name='network_edge_snapshots')
    op.drop_index(op.f('ix_network_edge_snapshots_edge_id'), table_name='network_edge_snapshots')
    op.drop_index(op.f('ix_network_edge_snapshots_destination_node_id'), table_name='network_edge_snapshots')
    op.drop_index('idx_net_edge_tenant_run', table_name='network_edge_snapshots')
    op.drop_table('network_edge_snapshots')

    # 32. lane_performance
    op.drop_index(op.f('ix_lane_performance_tenant_id'), table_name='lane_performance')
    op.drop_index(op.f('ix_lane_performance_run_id'), table_name='lane_performance')
    op.drop_index(op.f('ix_lane_performance_origin_id'), table_name='lane_performance')
    op.drop_index(op.f('ix_lane_performance_destination_id'), table_name='lane_performance')
    op.drop_index(op.f('ix_lane_performance_carrier_id'), table_name='lane_performance')
    op.drop_table('lane_performance')

    # 31. inventory_positions
    op.drop_index(op.f('ix_inventory_positions_tenant_id'), table_name='inventory_positions')
    op.drop_index(op.f('ix_inventory_positions_sku_id'), table_name='inventory_positions')
    op.drop_index(op.f('ix_inventory_positions_location_id'), table_name='inventory_positions')
    op.drop_index(op.f('ix_inventory_positions_ingestion_run_id'), table_name='inventory_positions')
    op.drop_table('inventory_positions')

    # 30. forecast_points
    op.drop_index(op.f('ix_forecast_points_tenant_id'), table_name='forecast_points')
    op.drop_index(op.f('ix_forecast_points_target_date'), table_name='forecast_points')
    op.drop_index(op.f('ix_forecast_points_sku_id'), table_name='forecast_points')
    op.drop_index(op.f('ix_forecast_points_location_id'), table_name='forecast_points')
    op.drop_index(op.f('ix_forecast_points_forecast_run_id'), table_name='forecast_points')
    op.drop_table('forecast_points')

    # 29. carrier_performance
    op.drop_index(op.f('ix_carrier_performance_tenant_id'), table_name='carrier_performance')
    op.drop_index(op.f('ix_carrier_performance_run_id'), table_name='carrier_performance')
    op.drop_index(op.f('ix_carrier_performance_carrier_id'), table_name='carrier_performance')
    op.drop_table('carrier_performance')

    # 28. supply_intelligence_runs
    op.drop_index(op.f('ix_supply_intelligence_runs_tenant_id'), table_name='supply_intelligence_runs')
    op.drop_index(op.f('ix_supply_intelligence_runs_id'), table_name='supply_intelligence_runs')
    op.drop_index(op.f('ix_supply_intelligence_runs_dataset_hash'), table_name='supply_intelligence_runs')
    op.drop_table('supply_intelligence_runs')

    # 27. suppliers
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_ingestion_run_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')

    # 26. scenario_runs
    op.drop_index(op.f('ix_scenario_runs_tenant_id'), table_name='scenario_runs')
    op.drop_index(op.f('ix_scenario_runs_scenario_id'), table_name='scenario_runs')
    op.drop_index(op.f('ix_scenario_runs_run_id'), table_name='scenario_runs')
    op.drop_index(op.f('ix_scenario_runs_id'), table_name='scenario_runs')
    op.drop_index('idx_scenario_tenant_run', table_name='scenario_runs')
    op.drop_table('scenario_runs')

    # 25. scenario_metric_snapshots
    op.drop_index(op.f('ix_scenario_metric_snapshots_tenant_id'), table_name='scenario_metric_snapshots')
    op.drop_index(op.f('ix_scenario_metric_snapshots_scenario_run_id'), table_name='scenario_metric_snapshots')
    op.drop_index(op.f('ix_scenario_metric_snapshots_id'), table_name='scenario_metric_snapshots')
    op.drop_index('idx_scenario_metric_tenant_run', table_name='scenario_metric_snapshots')
    op.drop_table('scenario_metric_snapshots')

    # 24. products
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku_code'), table_name='products')
    op.drop_index(op.f('ix_products_ingestion_run_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')

    # 23. prioritized_actions
    op.drop_index(op.f('ix_prioritized_actions_tenant_id'), table_name='prioritized_actions')
    op.drop_index(op.f('ix_prioritized_actions_run_id'), table_name='prioritized_actions')
    op.drop_index(op.f('ix_prioritized_actions_id'), table_name='prioritized_actions')
    op.drop_index('idx_action_tenant_run', table_name='prioritized_actions')
    op.drop_table('prioritized_actions')

    # 22. persistent_quarantine
    op.drop_index(op.f('ix_persistent_quarantine_tenant_id'), table_name='persistent_quarantine')
    op.drop_index(op.f('ix_persistent_quarantine_event_id'), table_name='persistent_quarantine')
    op.drop_table('persistent_quarantine')

    # 21. persistent_events
    op.drop_index(op.f('ix_persistent_events_tenant_id'), table_name='persistent_events')
    op.drop_index('ix_persistent_events_tenant_idem', table_name='persistent_events')
    op.drop_index(op.f('ix_persistent_events_idempotency_key'), table_name='persistent_events')
    op.drop_table('persistent_events')

    # 20. persistent_alerts
    op.drop_index(op.f('ix_persistent_alerts_tenant_id'), table_name='persistent_alerts')
    op.drop_index('ix_persistent_alerts_tenant_dedup', table_name='persistent_alerts')
    op.drop_index(op.f('ix_persistent_alerts_event_id'), table_name='persistent_alerts')
    op.drop_index(op.f('ix_persistent_alerts_deduplication_key'), table_name='persistent_alerts')
    op.drop_table('persistent_alerts')

    # 19. network_flow_runs
    op.drop_index(op.f('ix_network_flow_runs_tenant_id'), table_name='network_flow_runs')
    op.drop_index(op.f('ix_network_flow_runs_run_id'), table_name='network_flow_runs')
    op.drop_index(op.f('ix_network_flow_runs_dataset_hash'), table_name='network_flow_runs')
    op.drop_table('network_flow_runs')

    # 18. logistics_intelligence_runs
    op.drop_index(op.f('ix_logistics_intelligence_runs_tenant_id'), table_name='logistics_intelligence_runs')
    op.drop_index(op.f('ix_logistics_intelligence_runs_id'), table_name='logistics_intelligence_runs')
    op.drop_index(op.f('ix_logistics_intelligence_runs_dataset_hash'), table_name='logistics_intelligence_runs')
    op.drop_table('logistics_intelligence_runs')

    # 17. locations
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_ingestion_run_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')

    # 16. inventory_intelligence_runs
    op.drop_index(op.f('ix_inventory_intelligence_runs_tenant_id'), table_name='inventory_intelligence_runs')
    op.drop_index(op.f('ix_inventory_intelligence_runs_id'), table_name='inventory_intelligence_runs')
    op.drop_index(op.f('ix_inventory_intelligence_runs_forecast_run_id'), table_name='inventory_intelligence_runs')
    op.drop_index(op.f('ix_inventory_intelligence_runs_dataset_hash'), table_name='inventory_intelligence_runs')
    op.drop_table('inventory_intelligence_runs')

    # 15. intelligence_snapshots
    op.drop_index(op.f('ix_intelligence_snapshots_tenant_id'), table_name='intelligence_snapshots')
    op.drop_index(op.f('ix_intelligence_snapshots_run_id'), table_name='intelligence_snapshots')
    op.drop_index(op.f('ix_intelligence_snapshots_id'), table_name='intelligence_snapshots')
    op.drop_index('idx_snapshot_tenant_run', table_name='intelligence_snapshots')
    op.drop_table('intelligence_snapshots')

    # 14. intelligence_runs
    op.drop_index(op.f('ix_intelligence_runs_tenant_id'), table_name='intelligence_runs')
    op.drop_index(op.f('ix_intelligence_runs_id'), table_name='intelligence_runs')
    op.drop_index(op.f('ix_intelligence_runs_dataset_hash'), table_name='intelligence_runs')
    op.drop_index('idx_intel_run_tenant_hash', table_name='intelligence_runs')
    op.drop_table('intelligence_runs')

    # 13. ingestion_runs
    op.drop_index(op.f('ix_ingestion_runs_tenant_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_domain'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_data_hash'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')

    # 12. forecast_runs
    op.drop_index(op.f('ix_forecast_runs_tenant_id'), table_name='forecast_runs')
    op.drop_index(op.f('ix_forecast_runs_id'), table_name='forecast_runs')
    op.drop_index(op.f('ix_forecast_runs_dataset_hash'), table_name='forecast_runs')
    op.drop_table('forecast_runs')

    # 11. financial_intelligence_runs
    op.drop_index(op.f('ix_financial_intelligence_runs_tenant_id'), table_name='financial_intelligence_runs')
    op.drop_index(op.f('ix_financial_intelligence_runs_id'), table_name='financial_intelligence_runs')
    op.drop_index(op.f('ix_financial_intelligence_runs_dataset_hash'), table_name='financial_intelligence_runs')
    op.drop_index('idx_fin_run_tenant_hash', table_name='financial_intelligence_runs')
    op.drop_table('financial_intelligence_runs')

    # 10. financial_baseline_snapshots
    op.drop_index(op.f('ix_financial_baseline_snapshots_tenant_id'), table_name='financial_baseline_snapshots')
    op.drop_index(op.f('ix_financial_baseline_snapshots_run_id'), table_name='financial_baseline_snapshots')
    op.drop_index(op.f('ix_financial_baseline_snapshots_id'), table_name='financial_baseline_snapshots')
    op.drop_index('idx_fin_baseline_tenant_run', table_name='financial_baseline_snapshots')
    op.drop_table('financial_baseline_snapshots')

    # 9. executive_summaries
    op.drop_index(op.f('ix_executive_summaries_tenant_id'), table_name='executive_summaries')
    op.drop_index(op.f('ix_executive_summaries_run_id'), table_name='executive_summaries')
    op.drop_index(op.f('ix_executive_summaries_id'), table_name='executive_summaries')
    op.drop_index('idx_summary_tenant_run', table_name='executive_summaries')
    op.drop_table('executive_summaries')

    # 8. conversations
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index('idx_conversation_tenant', table_name='conversations')
    op.drop_table('conversations')

    # 7. conversation_messages
    op.drop_index(op.f('ix_conversation_messages_tenant_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index('idx_msg_tenant_conv', table_name='conversation_messages')
    op.drop_table('conversation_messages')

    # 6. capability_states
    op.drop_index(op.f('ix_capability_states_tenant_id'), table_name='capability_states')
    op.drop_index(op.f('ix_capability_states_run_id'), table_name='capability_states')
    op.drop_index(op.f('ix_capability_states_id'), table_name='capability_states')
    op.drop_index(op.f('ix_capability_states_capability_name'), table_name='capability_states')
    op.drop_index('idx_cap_state_tenant_run', table_name='capability_states')
    op.drop_index('idx_cap_state_tenant_name', table_name='capability_states')
    op.drop_table('capability_states')

    # 5. business_signals
    op.drop_index(op.f('ix_business_signals_tenant_id'), table_name='business_signals')
    op.drop_index(op.f('ix_business_signals_signal_type'), table_name='business_signals')
    op.drop_index(op.f('ix_business_signals_run_id'), table_name='business_signals')
    op.drop_index(op.f('ix_business_signals_id'), table_name='business_signals')
    op.drop_index('idx_signal_tenant_run', table_name='business_signals')
    op.drop_table('business_signals')

    # 4. ai_quota_reservations
    op.drop_index('ix_ai_quota_reservations_ledger_record_id', table_name='ai_quota_reservations')
    op.drop_index('ix_ai_reservation_tenant_ledger', table_name='ai_quota_reservations')
    op.drop_index('ix_ai_reservation_tenant_expires', table_name='ai_quota_reservations')
    op.drop_index('ix_ai_reservation_tenant_created', table_name='ai_quota_reservations')
    op.drop_index('ix_ai_reservation_tenant_status', table_name='ai_quota_reservations')
    op.drop_table('ai_quota_reservations')

    # 3. ai_usage_ledgers
    op.drop_index('ix_ai_ledger_tenant_reservation', table_name='ai_usage_ledgers')
    op.drop_index(op.f('ix_ai_usage_ledgers_tenant_id'), table_name='ai_usage_ledgers')
    op.drop_index(op.f('ix_ai_usage_ledgers_month_str'), table_name='ai_usage_ledgers')
    op.drop_index(op.f('ix_ai_usage_ledgers_date_str'), table_name='ai_usage_ledgers')
    op.drop_index('ix_ai_ledger_tenant_month', table_name='ai_usage_ledgers')
    op.drop_index('ix_ai_ledger_tenant_date', table_name='ai_usage_ledgers')
    op.drop_table('ai_usage_ledgers')

    # 2. ai_usage_policies
    op.drop_index(op.f('ix_ai_usage_policies_tenant_id'), table_name='ai_usage_policies')
    op.drop_table('ai_usage_policies')

    # 1. ai_audit_logs
    op.drop_index(op.f('ix_ai_audit_logs_tenant_id'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_id'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_conversation_id'), table_name='ai_audit_logs')
    op.drop_index('idx_ai_audit_tenant', table_name='ai_audit_logs')
    op.drop_table('ai_audit_logs')