"""Output contract schema for Phase 7B Multi-Echelon Decision & Optimization Engine."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from aurix_core.schema.phase5_contract import MissingInput, TrackedValue


class OptimizationStatus(str, Enum):
    """Status indicator for optimization/decision evaluation, avoiding false optimality claims."""

    RECOMMENDED = "RECOMMENDED"
    FEASIBLE = "FEASIBLE"
    INFEASIBLE = "INFEASIBLE"
    NOT_OPTIMIZABLE = "NOT_OPTIMIZABLE"
    NO_IMPROVEMENT = "NO_IMPROVEMENT"
    USER_INPUT_REQUIRED = "USER_INPUT_REQUIRED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION"


class FeasibilityStatus(str, Enum):
    """Feasibility categorization for constraint-satisfaction evaluations."""

    FEASIBLE = "FEASIBLE"
    INSUFFICIENT_INVENTORY = "INSUFFICIENT_INVENTORY"
    INSUFFICIENT_CAPACITY = "INSUFFICIENT_CAPACITY"
    MOQ_VIOLATION = "MOQ_VIOLATION"
    PACK_SIZE_VIOLATION = "PACK_SIZE_VIOLATION"
    NO_VALID_ROUTE = "NO_VALID_ROUTE"
    UNCONSTRAINED = "UNCONSTRAINED"


class DecisionType(str, Enum):
    """Categorization of decision recommendations generated by Phase 7B."""

    INVENTORY_REBALANCE = "INVENTORY_REBALANCE"
    SUPPLIER_REALLOCATION = "SUPPLIER_REALLOCATION"
    CAPACITY_REROUTE = "CAPACITY_REROUTE"
    MONITOR_ONLY = "MONITOR_ONLY"


class BaselineState(BaseModel):
    """Pre-optimization operational and financial ground truth for a node or echelon."""

    inventory_value: TrackedValue
    coverage_days: TrackedValue
    service_exposure_risk: TrackedValue
    bottleneck_active: bool = False


class OptimizedState(BaseModel):
    """Post-optimization projected operational and financial state following recommendation."""

    inventory_value: TrackedValue
    coverage_days: TrackedValue
    service_exposure_risk: TrackedValue
    bottleneck_active: bool = False


class OperationalImpact(BaseModel):
    """Quantified operational deltas between BaselineState and OptimizedState."""

    inventory_coverage_change_days: TrackedValue
    stockout_exposure_change: TrackedValue
    lead_time_change_days: TrackedValue
    service_level_change: TrackedValue


class FinancialImpact(BaseModel):
    """Quantified financial deltas strictly subject to Zero-Fabrication rules."""

    total_cost_change: TrackedValue
    working_capital_released: TrackedValue
    transportation_cost_change: TrackedValue
    currency: str = "USD"


class DecisionRecommendation(BaseModel):
    """Actionable supply chain recommendation generated by Phase 7B decision engines."""

    recommendation_id: str
    decision_type: DecisionType
    sku_id: str
    source_node: str
    destination_node: str
    quantity: float
    baseline: BaselineState
    optimized_state: OptimizedState
    operational_impact: OperationalImpact
    financial_impact: FinancialImpact
    feasibility: FeasibilityStatus
    evidence_quality: str
    timing_days: Optional[float] = None
    justification: List[str] = Field(default_factory=list)
    constraints_evaluated: List[str] = Field(default_factory=list)


class TradeoffOption(BaseModel):
    """Alternative decision scenario compared against the primary recommendation."""

    option_id: str
    description: str
    decision_type: DecisionType
    operational_impact: OperationalImpact
    financial_impact: FinancialImpact
    feasibility: FeasibilityStatus
    tradeoff_reason: str


class OptimizationResult(BaseModel):
    """SKU-level decision engine result container."""

    status: OptimizationStatus
    reason: str
    recommended_action: Optional[DecisionRecommendation] = None
    alternatives: List[TradeoffOption] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)


class Phase9InputContract(BaseModel):
    """System-level output contract for Phase 7B, serving as input for downstream presentation/execution."""

    status: str
    portfolio_financial_impact: FinancialImpact
    missing_inputs: List[MissingInput] = Field(default_factory=list)
    decisions: Dict[str, OptimizationResult] = Field(default_factory=dict)
    limitations: List[str] = Field(default_factory=list)
    provenance: Dict[str, Any] = Field(default_factory=dict)