import { CaseManagementReport } from '@/types/case.types';

export class CaseAdapter {
  public static generateSimulatedCases(): CaseManagementReport {
    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        totalOpenCases: 3,
        investigatingCount: 1,
        awaitingApprovalCount: 1,
        resolvedCount: 2,
        criticalPriorityCount: 1,
        aggregateExposureAtStakeINR: 384800,
      },
      cases: [
        {
          id: 'CASE-2026-084',
          title: 'Stockout Mitigation & Expedite Sizing for SKU-004',
          domain: 'Inventory Risk',
          priority: 'CRITICAL',
          stage: 'AWAITING_APPROVAL',
          owner: 'Supply Chain Operations',
          targetEntityId: 'SKU-004',
          targetEntityName: '103 Black-XXL (Hoodie)',
          alertId: 'ALT-9041',
          summary: 'Imminent buffer breach requires air freight dispatch authorization to prevent 98.4% service level failure.',
          rootCauseAttribution: 'Supplier delivery delay (+2.5d) intersecting with unforecasted Q4 festive spike (+20%).',
          exposureINR: 112500,
          serviceImpactPercent: 86.2,
          createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
          updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
          provenanceLineage: [
            {
              stepIndex: 1,
              stage: 'EVENT_DETECTED',
              title: 'Lead-Time & Consumption Deviation Detected',
              actorOrSystem: 'Deterministic Ingestion Engine',
              timestamp: '10:14 AM IST',
              summary: 'Daily sales velocity exceeded 3.8 pcs/day while inbound PO-2025-084 flagged delayed.',
            },
            {
              stepIndex: 2,
              stage: 'ALERT_TRIGGERED',
              title: 'Operational Alert ALT-9041 Generated',
              actorOrSystem: 'AURIX Alert Matrix',
              timestamp: '10:15 AM IST',
              summary: 'Breach window calculated at <= 6 calendar days.',
            },
            {
              stepIndex: 3,
              stage: 'CASE_ESCALATED',
              title: 'Formal Case CASE-2026-084 Provisioned',
              actorOrSystem: 'Executive Operator',
              timestamp: '10:45 AM IST',
              summary: 'Case opened with priority CRITICAL and assigned to Supply Chain Operations.',
            },
            {
              stepIndex: 4,
              stage: 'SCENARIO_SIMULATION',
              title: 'What-If Simulation Scenario A Formulated',
              actorOrSystem: 'Scenario Studio Engine',
              timestamp: '11:00 AM IST',
              summary: 'Air freight expedite of 300 units yields +7.2% SL recovery and ₹1.58L revenue protection.',
            },
            {
              stepIndex: 5,
              stage: 'AWAITING_APPROVAL',
              title: 'Phase 14 Preflight Cleared & Awaiting Signoff',
              actorOrSystem: 'Phase 14 Governance Engine',
              timestamp: '11:15 AM IST',
              summary: 'Execution payload prepared with cryptographic checksum sha256:e3b0c44...',
            },
          ],
        },
        {
          id: 'CASE-2026-082',
          title: 'Carrier Delay Remediation for Surat-BLR Freight Corridor',
          domain: 'Logistics',
          priority: 'HIGH',
          stage: 'INVESTIGATING',
          owner: 'Logistics Control Desk',
          targetEntityId: 'LANE-SUR-BLR',
          targetEntityName: 'Surat to Bengaluru Highway Corridor',
          alertId: 'ALT-9042',
          summary: 'Corridor disruption delaying PO-2025-084 batch; evaluating rerouting options.',
          rootCauseAttribution: 'Interstate checkpoint freight backlog and regional toll congestion.',
          exposureINR: 58200,
          serviceImpactPercent: 91.0,
          createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
          updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
          provenanceLineage: [
            {
              stepIndex: 1,
              stage: 'EVENT_DETECTED',
              title: 'GPS Milestone Telemetry Deviation',
              actorOrSystem: 'Carrier Webhook Listener',
              timestamp: '08:30 AM IST',
              summary: 'Vehicle stopped for > 18 hours outside Surat terminal.',
            },
            {
              stepIndex: 2,
              stage: 'INVESTIGATING',
              title: 'Carrier ETA Recalibrated',
              actorOrSystem: 'Logistics Planner',
              timestamp: '09:00 AM IST',
              summary: 'Contacted carrier dispatch desk to confirm alternate bypass routing.',
            },
          ],
        },
        {
          id: 'CASE-2026-079',
          title: 'Working Capital Right-Sizing & Markdown for SKU-005',
          domain: 'Inventory Economics',
          priority: 'MEDIUM',
          stage: 'RESOLVED',
          owner: 'Merchandising Team',
          targetEntityId: 'SKU-005',
          targetEntityName: '104 Olive-M (Jeans)',
          alertId: 'ALT-9044',
          summary: '15% digital markdown executed; 178 excess units liquidated over 45-day campaign.',
          rootCauseAttribution: 'Q3 batch over-procurement post festive surge.',
          exposureINR: 213600,
          serviceImpactPercent: 90.0,
          createdAt: new Date(Date.now() - 1000 * 60 * 1440 * 3).toISOString(),
          updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
          resolvedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
          provenanceLineage: [
            {
              stepIndex: 1,
              stage: 'RESOLVED',
              title: 'Markdown Workflow Concluded',
              actorOrSystem: 'ERP Financial Sync',
              timestamp: 'Yesterday 04:30 PM IST',
              summary: 'Target inventory level restored to 90 days cover.',
            },
          ],
        },
      ],
    };
  }
}