import { ControlTowerReport } from '@/types/control-tower.types';

export class ControlTowerAdapter {
  public static generateSimulatedControlTower(): ControlTowerReport {
    return {
      evaluatedAt: new Date().toISOString(),
      engineSyncStatus: 'SYNCHRONIZED',
      tenantId: 'ENTERPRISE_GLOBAL',
      financials: {
        grossInventoryValuationINR: 2762600,
        unlockedCapitalOpportunityINR: 388340,
        stockoutRevenueAtRiskINR: 170700,
        portfolioServiceLevelPercent: 95.4,
        serviceLevelTargetPercent: 95.0,
        activeBreachesCount: 3,
      },
      pillars: [
        {
          key: 'demand',
          title: 'Demand Health',
          status: 'OPTIMAL',
          primaryMetric: '5,030 pcs',
          metricLabel: 'Annual Volume',
          subText: 'Smooth stationary profile across 67% portfolio',
          routeHref: '/supply-chain?subdomain=demand-forecast',
        },
        {
          key: 'forecasting',
          title: 'ML Forecaster',
          status: 'OPTIMAL',
          primaryMetric: '91.8%',
          metricLabel: 'Model Accuracy',
          subText: 'XGBoost Ensemble validated champion (8.2% WAPE)',
          routeHref: '/supply-chain?subdomain=demand-forecast',
        },
        {
          key: 'inventory',
          title: 'Inventory Health',
          status: 'WATCH',
          primaryMetric: '83 Days',
          metricLabel: 'Mean Stock Cover',
          subText: '2 SKUs near ROP trigger; 1 excess variant',
          routeHref: '/inventory',
        },
        {
          key: 'supply',
          title: 'Supply Reliability',
          status: 'WATCH',
          primaryMetric: '83.4%',
          metricLabel: 'Vendor OTIF',
          subText: '1 elevated risk vendor (Vanguard Knits, P95=58d)',
          routeHref: '/supply-chain?subdomain=planning',
        },
        {
          key: 'lead_time',
          title: 'Lead-Time Health',
          status: 'OPTIMAL',
          primaryMetric: '28 Days',
          metricLabel: 'P50 Turnaround',
          subText: 'P90 variance contained within 34 days threshold',
          routeHref: '/supply-chain?subdomain=planning',
        },
        {
          key: 'logistics',
          title: 'Logistics & Transit',
          status: 'CRITICAL',
          primaryMetric: '2 Delayed',
          metricLabel: 'Active Shipments',
          subText: 'Surat-BLR & Chennai Port customs hold',
          routeHref: '/logistics',
        },
        {
          key: 'network',
          title: 'Network Topology',
          status: 'WATCH',
          primaryMetric: '1.90x',
          metricLabel: 'Bullwhip Tier-1',
          subText: 'Capacity bottleneck at Tiruppur processing mill',
          routeHref: '/supply-chain?subdomain=network',
        },
        {
          key: 'working_capital',
          title: 'Working Capital',
          status: 'OPTIMAL',
          primaryMetric: '₹3.88L',
          metricLabel: 'Cash Unlock',
          subText: 'Liquid capital recoverable via inventory rebalancing',
          routeHref: '/decisions/finance',
        },
      ],
      urgentSignals: [
        {
          id: 'SIG-01',
          title: 'Impending Stockout on High-Velocity SKU-004',
          targetEntity: '103 Black-XXL (Hoodie)',
          category: 'INVENTORY_BREACH',
          severity: 'CRITICAL',
          exposureINR: 112500,
          breachWindow: 'Breaches in 6 Days',
          prescriptiveSummary: 'Expedite 300 units via Air Cargo to recover 98.4% target service level.',
          recommendationRoute: '/decisions/recommendations',
        },
        {
          id: 'SIG-02',
          title: 'Freight Lane Congestion on Surat-Bengaluru Corridor',
          targetEntity: 'PO-2025-084 Manifest',
          category: 'LOGISTICS_DELAY',
          severity: 'HIGH',
          exposureINR: 58200,
          breachWindow: 'Delayed by +2.5 Days',
          prescriptiveSummary: 'Reroute inbound replenishment batch or adjust plant production queue.',
          recommendationRoute: '/logistics',
        },
        {
          id: 'SIG-03',
          title: 'Capital Trapped in Slow-Moving SKU-005 Inventory',
          targetEntity: '104 Olive-M (Jeans)',
          category: 'CAPITAL_LOCKUP',
          severity: 'WATCH',
          exposureINR: 213600,
          breachWindow: '331 Days Cover',
          prescriptiveSummary: 'Execute 15% targeted markdown and freeze procurement for 90 days.',
          recommendationRoute: '/decisions/recommendations',
        },
      ],
    };
  }
}