import { EdaAnalyticsReport, SkuDemandProfile, SeasonalityCell } from '@/types/eda.types';

export class EdaAdapter {
  public static generateSimulatedEda(): EdaAnalyticsReport {
    const skuProfiles: SkuDemandProfile[] = [
      {
        skuId: 'SKU-001',
        skuName: '101 Beige-L (T-Shirt)',
        category: 'T-Shirts',
        abcClass: 'A',
        xyzClass: 'Y',
        demandPattern: 'Smooth',
        totalVolume: 1420,
        totalRevenueINR: 596400,
        meanMonthlyDemand: 118.3,
        coefficientOfVariation: 0.28,
        zeroDemandMonths: 0,
        monthlyHistory: [
          { month: 'Jan', demand: 92, revenue: 38640 },
          { month: 'Feb', demand: 104, revenue: 43680 },
          { month: 'Mar', demand: 112, revenue: 47040 },
          { month: 'Apr', demand: 125, revenue: 52500 },
          { month: 'May', demand: 130, revenue: 54600 },
          { month: 'Jun', demand: 145, revenue: 60900 },
          { month: 'Jul', demand: 138, revenue: 57960 },
          { month: 'Aug', demand: 120, revenue: 50400 },
          { month: 'Sep', demand: 115, revenue: 48300 },
          { month: 'Oct', demand: 132, revenue: 55440 },
          { month: 'Nov', demand: 102, revenue: 42840 },
          { month: 'Dec', demand: 105, revenue: 44100 },
        ],
      },
      {
        skuId: 'SKU-002',
        skuName: '101 Beige-M (T-Shirt)',
        category: 'T-Shirts',
        abcClass: 'A',
        xyzClass: 'X',
        demandPattern: 'Smooth',
        totalVolume: 1850,
        totalRevenueINR: 777000,
        meanMonthlyDemand: 154.1,
        coefficientOfVariation: 0.14,
        zeroDemandMonths: 0,
        monthlyHistory: [
          { month: 'Jan', demand: 145, revenue: 60900 },
          { month: 'Feb', demand: 150, revenue: 63000 },
          { month: 'Mar', demand: 155, revenue: 65100 },
          { month: 'Apr', demand: 160, revenue: 67200 },
          { month: 'May', demand: 162, revenue: 68040 },
          { month: 'Jun', demand: 158, revenue: 66360 },
          { month: 'Jul', demand: 152, revenue: 63840 },
          { month: 'Aug', demand: 150, revenue: 63000 },
          { month: 'Sep', demand: 154, revenue: 64680 },
          { month: 'Oct', demand: 160, revenue: 67200 },
          { month: 'Nov', demand: 152, revenue: 63840 },
          { month: 'Dec', demand: 152, revenue: 63840 },
        ],
      },
      {
        skuId: 'SKU-003',
        skuName: '102 Navy-L (Polo)',
        category: 'Polos',
        abcClass: 'B',
        xyzClass: 'Y',
        demandPattern: 'Smooth',
        totalVolume: 840,
        totalRevenueINR: 487200,
        meanMonthlyDemand: 70.0,
        coefficientOfVariation: 0.34,
        zeroDemandMonths: 0,
        monthlyHistory: [
          { month: 'Jan', demand: 55, revenue: 31900 },
          { month: 'Feb', demand: 60, revenue: 34800 },
          { month: 'Mar', demand: 72, revenue: 41760 },
          { month: 'Apr', demand: 85, revenue: 49300 },
          { month: 'May', demand: 90, revenue: 52200 },
          { month: 'Jun', demand: 95, revenue: 55100 },
          { month: 'Jul', demand: 80, revenue: 46400 },
          { month: 'Aug', demand: 68, revenue: 39440 },
          { month: 'Sep', demand: 62, revenue: 35960 },
          { month: 'Oct', demand: 70, revenue: 40600 },
          { month: 'Nov', demand: 53, revenue: 30740 },
          { month: 'Dec', demand: 50, revenue: 29000 },
        ],
      },
      {
        skuId: 'SKU-004',
        skuName: '103 Black-XXL (Hoodie)',
        category: 'Hoodies',
        abcClass: 'B',
        xyzClass: 'Z',
        demandPattern: 'Intermittent',
        totalVolume: 420,
        totalRevenueINR: 378000,
        meanMonthlyDemand: 35.0,
        coefficientOfVariation: 0.82,
        zeroDemandMonths: 4,
        monthlyHistory: [
          { month: 'Jan', demand: 78, revenue: 70200 },
          { month: 'Feb', demand: 62, revenue: 55800 },
          { month: 'Mar', demand: 18, revenue: 16200 },
          { month: 'Apr', demand: 0, revenue: 0 },
          { month: 'May', demand: 0, revenue: 0 },
          { month: 'Jun', demand: 0, revenue: 0 },
          { month: 'Jul', demand: 0, revenue: 0 },
          { month: 'Aug', demand: 12, revenue: 10800 },
          { month: 'Sep', demand: 34, revenue: 30600 },
          { month: 'Oct', demand: 85, revenue: 76500 },
          { month: 'Nov', demand: 95, revenue: 85500 },
          { month: 'Dec', demand: 36, revenue: 32400 },
        ],
      },
      {
        skuId: 'SKU-005',
        skuName: '104 Olive-M (Jeans)',
        category: 'Jeans',
        abcClass: 'C',
        xyzClass: 'X',
        demandPattern: 'Smooth',
        totalVolume: 310,
        totalRevenueINR: 372000,
        meanMonthlyDemand: 25.8,
        coefficientOfVariation: 0.18,
        zeroDemandMonths: 0,
        monthlyHistory: [
          { month: 'Jan', demand: 24, revenue: 28800 },
          { month: 'Feb', demand: 26, revenue: 31200 },
          { month: 'Mar', demand: 25, revenue: 30000 },
          { month: 'Apr', demand: 28, revenue: 33600 },
          { month: 'May', demand: 27, revenue: 32400 },
          { month: 'Jun', demand: 26, revenue: 31200 },
          { month: 'Jul', demand: 25, revenue: 30000 },
          { month: 'Aug', demand: 24, revenue: 28800 },
          { month: 'Sep', demand: 26, revenue: 31200 },
          { month: 'Oct', demand: 28, revenue: 33600 },
          { month: 'Nov', demand: 26, revenue: 31200 },
          { month: 'Dec', demand: 25, revenue: 30000 },
        ],
      },
      {
        skuId: 'SKU-006',
        skuName: '105 Charcoal-L (Track Pants)',
        category: 'Track Pants',
        abcClass: 'C',
        xyzClass: 'Z',
        demandPattern: 'Lumpy',
        totalVolume: 190,
        totalRevenueINR: 152000,
        meanMonthlyDemand: 15.8,
        coefficientOfVariation: 0.95,
        zeroDemandMonths: 3,
        monthlyHistory: [
          { month: 'Jan', demand: 0, revenue: 0 },
          { month: 'Feb', demand: 42, revenue: 33600 },
          { month: 'Mar', demand: 0, revenue: 0 },
          { month: 'Apr', demand: 18, revenue: 14400 },
          { month: 'May', demand: 0, revenue: 0 },
          { month: 'Jun', demand: 32, revenue: 25600 },
          { month: 'Jul', demand: 15, revenue: 12000 },
          { month: 'Aug', demand: 10, revenue: 8000 },
          { month: 'Sep', demand: 8, revenue: 6400 },
          { month: 'Oct', demand: 25, revenue: 20000 },
          { month: 'Nov', demand: 22, revenue: 17600 },
          { month: 'Dec', demand: 18, revenue: 14400 },
        ],
      },
    ];

    const seasonality: SeasonalityCell[] = [
      { month: 'Jan', quarter: 'Q1', averageIndex: 0.92, peakCategory: 'Hoodies' },
      { month: 'Feb', quarter: 'Q1', averageIndex: 0.98, peakCategory: 'Hoodies' },
      { month: 'Mar', quarter: 'Q1', averageIndex: 1.05, peakCategory: 'Polos' },
      { month: 'Apr', quarter: 'Q2', averageIndex: 1.18, peakCategory: 'T-Shirts' },
      { month: 'May', quarter: 'Q2', averageIndex: 1.25, peakCategory: 'T-Shirts' },
      { month: 'Jun', quarter: 'Q2', averageIndex: 1.32, peakCategory: 'T-Shirts' },
      { month: 'Jul', quarter: 'Q3', averageIndex: 1.10, peakCategory: 'Polos' },
      { month: 'Aug', quarter: 'Q3', averageIndex: 0.88, peakCategory: 'Jeans' },
      { month: 'Sep', quarter: 'Q3', averageIndex: 0.95, peakCategory: 'Jeans' },
      { month: 'Oct', quarter: 'Q4', averageIndex: 1.28, peakCategory: 'Hoodies' },
      { month: 'Nov', quarter: 'Q4', averageIndex: 1.35, peakCategory: 'Hoodies' },
      { month: 'Dec', quarter: 'Q4', averageIndex: 0.94, peakCategory: 'Jeans' },
    ];

    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        totalSkus: 6,
        totalAnnualVolume: 5030,
        totalAnnualRevenueINR: 2762600,
        portfolioMeanCV: 0.45,
        intermittentSkuCount: 2,
        abcDistribution: { classA: 2, classB: 2, classC: 2 },
        xyzDistribution: { classX: 2, classY: 2, classZ: 2 },
      },
      skuProfiles,
      seasonality,
    };
  }
}