import { FulfillmentReport } from '@/types/fulfillment.types';

export class FulfillmentAdapter {
  public static generateSimulatedFulfillment(): FulfillmentReport {
    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        totalOrdersCount: 5,
        onTimeFulfillmentRatePercent: 92.4,
        backorderedUnitsCount: 145,
        totalOrderValueINR: 894000,
        allocatedRevenueINR: 762000,
        immediateAtpCoveragePercent: 88.0,
      },
      orders: [
        {
          orderId: 'ORD-2025-9941',
          customerName: 'Myntra Omnichannel Fulfillment',
          channel: 'E-COMMERCE',
          orderDate: '2025-02-14',
          promisedDate: '2025-02-16',
          skuId: 'SKU-001',
          skuName: '101 Beige-L (T-Shirt)',
          orderedUnits: 250,
          allocatedUnits: 250,
          totalAmountINR: 105000,
          status: 'ALLOCATED',
          allocationPercent: 100,
          shippingPriority: 'EXPEDITED',
        },
        {
          orderId: 'ORD-2025-9942',
          customerName: 'Lifestyle International B2B',
          channel: 'B2B_WHOLESALE',
          orderDate: '2025-02-13',
          promisedDate: '2025-02-17',
          skuId: 'SKU-002',
          skuName: '101 Beige-M (T-Shirt)',
          orderedUnits: 300,
          allocatedUnits: 165,
          totalAmountINR: 126000,
          status: 'PARTIALLY_ALLOCATED',
          allocationPercent: 55,
          shippingPriority: 'STANDARD',
        },
        {
          orderId: 'ORD-2025-9943',
          customerName: 'Direct Omnichannel D2C Batch',
          channel: 'E-COMMERCE',
          orderDate: '2025-02-14',
          promisedDate: '2025-02-15',
          skuId: 'SKU-004',
          skuName: '103 Black-XXL (Hoodie)',
          orderedUnits: 180,
          allocatedUnits: 42,
          totalAmountINR: 162000,
          status: 'BACKORDERED',
          allocationPercent: 23,
          shippingPriority: 'SAME_DAY',
        },
        {
          orderId: 'ORD-2025-9944',
          customerName: 'Shoppers Stop Retail Consignment',
          channel: 'RETAIL_STORE',
          orderDate: '2025-02-12',
          promisedDate: '2025-02-18',
          skuId: 'SKU-003',
          skuName: '102 Navy-L (Polo)',
          orderedUnits: 120,
          allocatedUnits: 120,
          totalAmountINR: 69600,
          status: 'ALLOCATED',
          allocationPercent: 100,
          shippingPriority: 'STANDARD',
        },
        {
          orderId: 'ORD-2025-9940',
          customerName: 'Ajio Wholesale Distribution',
          channel: 'B2B_WHOLESALE',
          orderDate: '2025-02-10',
          promisedDate: '2025-02-14',
          skuId: 'SKU-005',
          skuName: '104 Olive-M (Jeans)',
          orderedUnits: 200,
          allocatedUnits: 200,
          totalAmountINR: 240000,
          status: 'FULFILLED',
          allocationPercent: 100,
          shippingPriority: 'STANDARD',
        },
      ],
    };
  }
}