import { InventoryAnalyticsReport, SkuInventoryMetrics } from '@/types/inventory.types';

export class InventoryAdapter {
  public static generateSimulatedInventory(): InventoryAnalyticsReport {
    const skuInventories: SkuInventoryMetrics[] = [
      {
        skuId: 'SKU-001',
        skuName: '101 Beige-L (T-Shirt)',
        category: 'T-Shirts',
        currentStockUnits: 327,
        safetyStockUnits: 84,
        reorderPointUnits: 196,
        economicOrderQty: 250,
        averageDailyDemand: 3.94,
        daysOfCoverRemaining: 83,
        serviceLevelTargetPercent: 95.0,
        stockoutProbabilityPercent: 2.1,
        stockoutBreachDays: null,
        excessStockUnits: 47,
        capitalTiedUpINR: 137340,
        excessCapitalExposureINR: 19740,
        stockoutRevenueAtRiskINR: 0,
        healthStatus: 'OPTIMAL',
        leadTimeDaysUsed: 28,
        recommendationAction: 'Maintain steady-state replenishment. No immediate PO required.',
      },
      {
        skuId: 'SKU-002',
        skuName: '101 Beige-M (T-Shirt)',
        category: 'T-Shirts',
        currentStockUnits: 165,
        safetyStockUnits: 96,
        reorderPointUnits: 245,
        economicOrderQty: 300,
        averageDailyDemand: 5.14,
        daysOfCoverRemaining: 32,
        serviceLevelTargetPercent: 98.0,
        stockoutProbabilityPercent: 28.4,
        stockoutBreachDays: 14,
        excessStockUnits: 0,
        capitalTiedUpINR: 69300,
        excessCapitalExposureINR: 0,
        stockoutRevenueAtRiskINR: 58200,
        healthStatus: 'RISK_OF_STOCKOUT',
        leadTimeDaysUsed: 28,
        recommendationAction: 'Trigger Purchase Order for 300 units immediately to avoid stockout on Day 14.',
      },
      {
        skuId: 'SKU-003',
        skuName: '102 Navy-L (Polo)',
        category: 'Polos',
        currentStockUnits: 138,
        safetyStockUnits: 45,
        reorderPointUnits: 115,
        economicOrderQty: 180,
        averageDailyDemand: 2.33,
        daysOfCoverRemaining: 59,
        serviceLevelTargetPercent: 95.0,
        stockoutProbabilityPercent: 4.8,
        stockoutBreachDays: null,
        excessStockUnits: 0,
        capitalTiedUpINR: 80040,
        excessCapitalExposureINR: 0,
        stockoutRevenueAtRiskINR: 0,
        healthStatus: 'OPTIMAL',
        leadTimeDaysUsed: 30,
        recommendationAction: 'Inventory position balanced. Reorder scheduled in 21 days.',
      },
      {
        skuId: 'SKU-004',
        skuName: '103 Black-XXL (Hoodie)',
        category: 'Hoodies',
        currentStockUnits: 42,
        safetyStockUnits: 65,
        reorderPointUnits: 140,
        economicOrderQty: 120,
        averageDailyDemand: 2.85,
        daysOfCoverRemaining: 15,
        serviceLevelTargetPercent: 95.0,
        stockoutProbabilityPercent: 74.2,
        stockoutBreachDays: 6,
        excessStockUnits: 0,
        capitalTiedUpINR: 37800,
        excessCapitalExposureINR: 0,
        stockoutRevenueAtRiskINR: 112500,
        healthStatus: 'CRITICAL_BREACH',
        leadTimeDaysUsed: 35,
        recommendationAction: 'EXPEDITE INBOUND SHIPMENT: Stockout projected within 6 days during high-season surge.',
      },
      {
        skuId: 'SKU-005',
        skuName: '104 Olive-M (Jeans)',
        category: 'Jeans',
        currentStockUnits: 285,
        safetyStockUnits: 32,
        reorderPointUnits: 75,
        economicOrderQty: 100,
        averageDailyDemand: 0.86,
        daysOfCoverRemaining: 331,
        serviceLevelTargetPercent: 90.0,
        stockoutProbabilityPercent: 0.2,
        stockoutBreachDays: null,
        excessStockUnits: 178,
        capitalTiedUpINR: 342000,
        excessCapitalExposureINR: 213600,
        stockoutRevenueAtRiskINR: 0,
        healthStatus: 'EXCESS_INVENTORY',
        leadTimeDaysUsed: 45,
        recommendationAction: 'Capital constrained by 178 excess units. Halt future POs for 90 days.',
      },
    ];

    const totalValuation = skuInventories.reduce((acc, s) => acc + s.capitalTiedUpINR, 0);
    const totalExcess = skuInventories.reduce((acc, s) => acc + s.excessCapitalExposureINR, 0);
    const totalAtRisk = skuInventories.reduce((acc, s) => acc + s.stockoutRevenueAtRiskINR, 0);

    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        totalInventoryValuationINR: totalValuation,
        totalWorkingCapitalExcessINR: totalExcess,
        totalStockoutExposureINR: totalAtRisk,
        portfolioServiceLevelPercent: 95.4,
        skusAtStockoutRiskCount: 2,
        skusWithExcessStockCount: 1,
        skusOptimalCount: 2,
      },
      skuInventories,
    };
  }
}