import { LogisticsAnalyticsReport } from '@/types/logistics.types';
import { ApiClient } from '@/services/api/apiClient';

export class LogisticsAdapter {
  public static generateSimulatedLogistics(): LogisticsAnalyticsReport {
    const isMock = ApiClient.getMode() === 'MOCK';

    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        totalActiveShipments: isMock ? 6 : 0,
        totalInTransitUnits: isMock ? 3450 : 0,
        totalInTransitValuationINR: isMock ? 1845000 : 0,
        shipmentsAtDelayRiskCount: isMock ? 2 : 0,
        portfolioOnTimeTransitPercent: isMock ? 88.5 : 100.0,
      },
      lanes: isMock ? [
        {
          laneId: 'LANE-BLR-DEL',
          origin: 'Bengaluru Central Plant',
          destination: 'Delhi NCR Fulfillment Hub',
          mode: 'Road Freight',
          avgTransitDays: 3.4,
          p90TransitDays: 4.8,
          onTimeReliabilityPercent: 93.5,
          riskLevel: 'LOW',
          activeShipmentsCount: 3,
          totalUnitsInTransit: 1850,
          totalCapitalInTransitINR: 925000,
        },
        {
          laneId: 'LANE-SUR-BLR',
          origin: 'Surat Fabric Mill',
          destination: 'Bengaluru Central Plant',
          mode: 'Road Freight',
          avgTransitDays: 4.2,
          p90TransitDays: 6.5,
          onTimeReliabilityPercent: 81.0,
          riskLevel: 'MODERATE',
          activeShipmentsCount: 2,
          totalUnitsInTransit: 1200,
          totalCapitalInTransitINR: 680000,
        },
        {
          laneId: 'LANE-CHN-MUM',
          origin: 'Chennai Port Terminal',
          destination: 'Mumbai West Distribution Hub',
          mode: 'Ocean Express',
          avgTransitDays: 7.8,
          p90TransitDays: 12.0,
          onTimeReliabilityPercent: 68.0,
          riskLevel: 'CRITICAL',
          activeShipmentsCount: 1,
          totalUnitsInTransit: 400,
          totalCapitalInTransitINR: 240000,
        },
      ] : [],
      shipments: isMock ? [
        {
          trackingId: 'TRK-90214',
          poNumber: 'PO-2025-084',
          originHub: 'Surat Fabric Mill',
          destinationHub: 'Bengaluru Central Plant',
          transportMode: 'Road Freight',
          carrierName: 'Gati KWE Express',
          skuCount: 4,
          totalUnits: 650,
          shipmentValueINR: 375000,
          status: 'DELAYED',
          dispatchedDate: '2025-02-12',
          estimatedArrival: '2025-02-18',
          delayVarianceDays: 2.5,
          delayProbabilityPercent: 84.0,
        },
        {
          trackingId: 'TRK-90215',
          poNumber: 'PO-2025-089',
          originHub: 'Bengaluru Central Plant',
          destinationHub: 'Delhi NCR Hub',
          transportMode: 'Road Freight',
          carrierName: 'Delhivery Supply Chain',
          skuCount: 6,
          totalUnits: 850,
          shipmentValueINR: 425000,
          status: 'IN_TRANSIT',
          dispatchedDate: '2025-02-14',
          estimatedArrival: '2025-02-17',
          delayVarianceDays: 0.0,
          delayProbabilityPercent: 8.5,
        },
        {
          trackingId: 'TRK-90218',
          poNumber: 'PO-2025-092',
          originHub: 'Chennai Port Terminal',
          destinationHub: 'Mumbai West Hub',
          transportMode: 'Ocean Express',
          carrierName: 'Maersk Regional Feeder',
          skuCount: 2,
          totalUnits: 400,
          shipmentValueINR: 240000,
          status: 'CUSTOMS_HOLD',
          dispatchedDate: '2025-02-08',
          estimatedArrival: '2025-02-21',
          delayVarianceDays: 4.0,
          delayProbabilityPercent: 92.0,
        },
      ] : [],
    };
  }
}
