

export class ManufacturingAdapter {
  public static generateSimulatedManufacturing(): any {
    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        activePlannedOrdersCount: 8,
        meanPlantYieldRatePercent: 96.4,
        bottleneckWorkCentersCount: 1,
        criticalMaterialShortagesCount: 2,
        totalProductionCapacityHours: 1280,
        aggregatePlannedProductionUnits: 4850,
      },
      boms: [
        {
          parentSkuId: 'SKU-001',
          parentSkuName: '101 Beige-L (T-Shirt)',
          category: 'T-Shirts',
          version: 'BOM-v2.4',
          yieldRatePercent: 97.2,
          totalBomCostINR: 198.5,
          components: [
            {
              componentId: 'RAW-FAB-001',
              componentName: '180 GSM Single Jersey Combed Cotton (Beige)',
              level: 1,
              quantityPerParent: 0.38,
              unitOfMeasure: 'kg',
              scrapFactorPercent: 3.5,
              unitCostINR: 420,
              extendedCostINR: 159.6,
              leadTimeDays: 18,
              supplierName: 'Apex Mills & Fabrics Pvt Ltd',
              category: 'FABRIC',
            },
            {
              componentId: 'RAW-TRM-002',
              componentName: 'Spun Polyester Sewing Thread (Matching 40/2)',
              level: 2,
              quantityPerParent: 120,
              unitOfMeasure: 'meters',
              scrapFactorPercent: 5.0,
              unitCostINR: 0.08,
              extendedCostINR: 9.6,
              leadTimeDays: 7,
              supplierName: 'Vardhman Threads Ltd',
              category: 'TRIM',
            },
            {
              componentId: 'RAW-TRM-003',
              componentName: 'Woven Satin Brand & Care Label (AURIX/Quidch)',
              level: 2,
              quantityPerParent: 2,
              unitOfMeasure: 'pcs',
              scrapFactorPercent: 1.0,
              unitCostINR: 3.2,
              extendedCostINR: 6.4,
              leadTimeDays: 14,
              supplierName: 'TrimCraft Labels Pvt Ltd',
              category: 'TRIM',
            },
            {
              componentId: 'RAW-PKG-004',
              componentName: 'Biodegradable 50-Micron Apparel Polybag',
              level: 2,
              quantityPerParent: 1,
              unitOfMeasure: 'pcs',
              scrapFactorPercent: 0.5,
              unitCostINR: 4.5,
              extendedCostINR: 4.5,
              leadTimeDays: 5,
              supplierName: 'EcoPack India Ltd',
              category: 'PACKAGING',
            },
            {
              componentId: 'RAW-CHM-005',
              componentName: 'Softener & Silicone Enzyme Finishing Wash',
              level: 1,
              quantityPerParent: 0.05,
              unitOfMeasure: 'liters',
              scrapFactorPercent: 2.0,
              unitCostINR: 368,
              extendedCostINR: 18.4,
              leadTimeDays: 10,
              supplierName: 'Apex Chemical Finishes',
              category: 'CHEMICAL',
            },
          ],
        },
        {
          parentSkuId: 'SKU-004',
          parentSkuName: '103 Black-XXL (Hoodie)',
          category: 'Hoodies',
          version: 'BOM-v1.8',
          yieldRatePercent: 94.8,
          totalBomCostINR: 412.0,
          components: [
            {
              componentId: 'RAW-FAB-008',
              componentName: '340 GSM Heavyweight Brushed Cotton Fleece (Black)',
              level: 1,
              quantityPerParent: 0.85,
              unitOfMeasure: 'kg',
              scrapFactorPercent: 5.2,
              unitCostINR: 380,
              extendedCostINR: 323.0,
              leadTimeDays: 28,
              supplierName: 'Vanguard Knits & Fleece Ltd',
              category: 'FABRIC',
            },
            {
              componentId: 'RAW-TRM-011',
              componentName: 'Gunmetal Heavy-Duty Metal Zipper (YKK #5)',
              level: 2,
              quantityPerParent: 1,
              unitOfMeasure: 'pcs',
              scrapFactorPercent: 2.0,
              unitCostINR: 48.0,
              extendedCostINR: 48.0,
              leadTimeDays: 21,
              supplierName: 'YKK India Pvt Ltd',
              category: 'TRIM',
            },
            {
              componentId: 'RAW-TRM-012',
              componentName: 'Tubular Braided Cotton Drawcord with Metal Aglets',
              level: 2,
              quantityPerParent: 1.4,
              unitOfMeasure: 'meters',
              scrapFactorPercent: 2.5,
              unitCostINR: 12.0,
              extendedCostINR: 16.8,
              leadTimeDays: 10,
              supplierName: 'TrimCraft Labels Pvt Ltd',
              category: 'TRIM',
            },
            {
              componentId: 'RAW-PKG-004',
              componentName: 'Biodegradable 50-Micron Apparel Polybag',
              level: 2,
              quantityPerParent: 1,
              unitOfMeasure: 'pcs',
              scrapFactorPercent: 0.5,
              unitCostINR: 4.5,
              extendedCostINR: 4.5,
              leadTimeDays: 5,
              supplierName: 'EcoPack India Ltd',
              category: 'PACKAGING',
            },
            {
              componentId: 'RAW-TRM-003',
              componentName: 'Woven Satin Brand & Care Label (AURIX/Quidch)',
              level: 2,
              quantityPerParent: 2,
              unitOfMeasure: 'pcs',
              scrapFactorPercent: 1.0,
              unitCostINR: 3.2,
              extendedCostINR: 6.4,
              leadTimeDays: 14,
              supplierName: 'TrimCraft Labels Pvt Ltd',
              category: 'TRIM',
            },
          ],
        },
      ],
      mrpPlans: [
        {
          skuId: 'SKU-001',
          skuName: '101 Beige-L (T-Shirt)',
          leadTimeDays: 14,
          safetyStockUnits: 84,
          lotSizeRule: 'Fixed Batch (250 pcs)',
          startingOnHand: 327,
          timeBuckets: [
            {
              periodLabel: 'W1 (Current)',
              grossRequirements: 45,
              scheduledReceipts: 0,
              projectedAvailableBalance: 282,
              netRequirements: 0,
              plannedOrderReceipts: 0,
              plannedOrderReleases: 0,
            },
            {
              periodLabel: 'W2 (+7d)',
              grossRequirements: 52,
              scheduledReceipts: 0,
              projectedAvailableBalance: 230,
              netRequirements: 0,
              plannedOrderReceipts: 0,
              plannedOrderReleases: 0,
            },
            {
              periodLabel: 'W3 (+14d)',
              grossRequirements: 60,
              scheduledReceipts: 0,
              projectedAvailableBalance: 170,
              netRequirements: 0,
              plannedOrderReceipts: 0,
              plannedOrderReleases: 250,
            },
            {
              periodLabel: 'W4 (+21d)',
              grossRequirements: 58,
              scheduledReceipts: 0,
              projectedAvailableBalance: 112,
              netRequirements: 0,
              plannedOrderReceipts: 0,
              plannedOrderReleases: 0,
            },
            {
              periodLabel: 'W5 (+28d)',
              grossRequirements: 64,
              scheduledReceipts: 250,
              projectedAvailableBalance: 298,
              netRequirements: 0,
              plannedOrderReceipts: 250,
              plannedOrderReleases: 0,
            },
            {
              periodLabel: 'W6 (+35d)',
              grossRequirements: 70,
              scheduledReceipts: 0,
              projectedAvailableBalance: 228,
              netRequirements: 0,
              plannedOrderReceipts: 0,
              plannedOrderReleases: 0,
            },
          ],
        },
        {
          skuId: 'SKU-004',
          skuName: '103 Black-XXL (Hoodie)',
          leadTimeDays: 21,
          safetyStockUnits: 65,
          lotSizeRule: 'Fixed Batch (150 pcs)',
          startingOnHand: 42,
          timeBuckets: [
            {
              periodLabel: 'W1 (Current)',
              grossRequirements: 35,
              scheduledReceipts: 0,
              projectedAvailableBalance: 7,
              netRequirements: 58, // Safety stock breached
              plannedOrderReceipts: 0,
              plannedOrderReleases: 150, // Immediate planned release needed
            },
            {
              periodLabel: 'W2 (+7d)',
              grossRequirements: 42,
              scheduledReceipts: 0,
              projectedAvailableBalance: -35,
              netRequirements: 100,
              plannedOrderReceipts: 0,
              plannedOrderReleases: 150,
            },
            {
              periodLabel: 'W3 (+14d)',
              grossRequirements: 48,
              scheduledReceipts: 0,
              projectedAvailableBalance: -83,
              netRequirements: 148,
              plannedOrderReceipts: 0,
              plannedOrderReleases: 0,
            },
            {
              periodLabel: 'W4 (+21d)',
              grossRequirements: 50,
              scheduledReceipts: 150,
              projectedAvailableBalance: 17,
              netRequirements: 48,
              plannedOrderReceipts: 150,
              plannedOrderReleases: 0,
            },
            {
              periodLabel: 'W5 (+28d)',
              grossRequirements: 45,
              scheduledReceipts: 150,
              projectedAvailableBalance: 122,
              netRequirements: 0,
              plannedOrderReceipts: 150,
              plannedOrderReleases: 0,
            },
            {
              periodLabel: 'W6 (+35d)',
              grossRequirements: 40,
              scheduledReceipts: 0,
              projectedAvailableBalance: 82,
              netRequirements: 0,
              plannedOrderReceipts: 0,
              plannedOrderReleases: 0,
            },
          ],
        },
      ],
      workCenters: [
        {
          workCenterId: 'WC-CUT-01',
          workCenterName: 'Automated Fabric CNC Spreading & Cutting Unit',
          facilityLocation: 'Bengaluru Central Plant - Bay 1',
          weeklyCapacityHours: 320,
          allocatedLoadHours: 245,
          utilizationPercent: 76.5,
          isBottleneck: false,
          status: 'OPTIMAL',
          primaryConstrainingOperation: 'CAD nesting cycle time',
        },
        {
          workCenterId: 'WC-DYE-02',
          workCenterName: 'Soft-Flow Reactive Batch Dyeing Vessel',
          facilityLocation: 'Tiruppur Processing Mill - Line 3',
          weeklyCapacityHours: 280,
          allocatedLoadHours: 265,
          utilizationPercent: 94.6,
          isBottleneck: true,
          status: 'CRITICAL',
          primaryConstrainingOperation: 'Color matching and liquor ratio equilibration',
        },
        {
          workCenterId: 'WC-STC-03',
          workCenterName: 'Precision 4-Thread Overlock & Flatlock Stitching Lines',
          facilityLocation: 'Bengaluru Central Plant - Floor 2',
          weeklyCapacityHours: 480,
          allocatedLoadHours: 395,
          utilizationPercent: 82.3,
          isBottleneck: false,
          status: 'OPTIMAL',
          primaryConstrainingOperation: 'Operator manual needle changeovers',
        },
        {
          workCenterId: 'WC-FIN-04',
          workCenterName: 'Steam Tunnel Pressing, QC & RFID Packaging',
          facilityLocation: 'Bengaluru Central Plant - Bay 4',
          weeklyCapacityHours: 200,
          allocatedLoadHours: 156,
          utilizationPercent: 78.0,
          isBottleneck: false,
          status: 'OPTIMAL',
          primaryConstrainingOperation: 'RFID validation gate throughput',
        },
      ],
      exceptions: [
        {
          exceptionId: 'EXC-MRP-01',
          severity: 'CRITICAL',
          skuId: 'SKU-004',
          skuName: '103 Black-XXL (Hoodie)',
          period: 'W1 (Current Horizon)',
          message: 'Projected Available Balance (-35u) drops below Safety Stock (65u) in W2 without expedite.',
          suggestedRemediation: 'Advance planned release of 150 units immediately via expedited cutting schedule.',
          detectedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        },
        {
          exceptionId: 'EXC-CAP-02',
          severity: 'WARNING',
          skuId: 'WC-DYE-02',
          skuName: 'Reactive Batch Dyeing Line',
          period: 'Next 14 Days',
          message: 'Allocated load (94.6%) exceeds safe 90% threshold. Downstream stitching queues will stall.',
          suggestedRemediation: 'Offload 30% lot volume to pre-qualified secondary vendor DenimCraft.',
          detectedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
        },
      ],
    };
  }
}