import { ProcurementReport } from '@/types/procurement.types';

export class ProcurementAdapter {
  public static generateSimulatedProcurement(): ProcurementReport {
    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        totalOpenOrdersCount: 4,
        activeInboundValueINR: 1485000,
        threeWayMatchPassRatePercent: 94.2,
        pendingAsnCount: 3,
        criticalDelayedOrdersCount: 1,
        reconciledOrdersCount: 18,
      },
      purchaseOrders: [
        {
          poNumber: 'PO-2025-084',
          vendorId: 'VEND-001',
          vendorName: 'Apex Mills & Fabrics Pvt Ltd',
          status: 'IN_TRANSIT',
          orderDate: '2025-02-05',
          promisedDeliveryDate: '2025-02-16',
          revisedEtaDate: '2025-02-18',
          totalAmountINR: 375000,
          currency: 'INR',
          paymentTerms: 'Net 45 Days',
          inboundCarrier: 'Gati KWE Express',
          trackingNumber: 'TRK-90214',
          asnNumber: 'ASN-8841',
          lineItems: [
            {
              lineId: 'LINE-01',
              skuId: 'SKU-001',
              skuName: '101 Beige-L (T-Shirt)',
              orderedQty: 500,
              receivedQty: 0,
              invoicedQty: 500,
              unitPriceINR: 420,
              totalPriceINR: 210000,
            },
            {
              lineId: 'LINE-02',
              skuId: 'SKU-002',
              skuName: '101 Beige-M (T-Shirt)',
              orderedQty: 392,
              receivedQty: 0,
              invoicedQty: 392,
              unitPriceINR: 420,
              totalPriceINR: 165000,
            },
          ],
        },
        {
          poNumber: 'PO-2025-089',
          vendorId: 'VEND-002',
          vendorName: 'Vanguard Knits & Fleece Ltd',
          status: 'ACKNOWLEDGED',
          orderDate: '2025-02-10',
          promisedDeliveryDate: '2025-02-28',
          totalAmountINR: 425000,
          currency: 'INR',
          paymentTerms: 'Net 30 Days',
          inboundCarrier: 'Delhivery Supply Chain',
          trackingNumber: 'TRK-90215',
          asnNumber: 'ASN-8849',
          lineItems: [
            {
              lineId: 'LINE-01',
              skuId: 'SKU-004',
              skuName: '103 Black-XXL (Hoodie)',
              orderedQty: 450,
              receivedQty: 0,
              invoicedQty: 0,
              unitPriceINR: 944,
              totalPriceINR: 425000,
            },
          ],
        },
        {
          poNumber: 'PO-2025-092',
          vendorId: 'VEND-003',
          vendorName: 'DenimCraft Apparel Solutions',
          status: 'RECEIVED',
          orderDate: '2025-01-20',
          promisedDeliveryDate: '2025-02-14',
          totalAmountINR: 445000,
          currency: 'INR',
          paymentTerms: 'Net 60 Days',
          inboundCarrier: 'VRL Logistics',
          trackingNumber: 'TRK-90201',
          asnNumber: 'ASN-8820',
          lineItems: [
            {
              lineId: 'LINE-01',
              skuId: 'SKU-005',
              skuName: '104 Olive-M (Jeans)',
              orderedQty: 370,
              receivedQty: 370,
              invoicedQty: 370,
              unitPriceINR: 1200,
              totalPriceINR: 445000,
            },
          ],
        },
        {
          poNumber: 'PO-2025-095',
          vendorId: 'VEND-001',
          vendorName: 'Apex Mills & Fabrics Pvt Ltd',
          status: 'ISSUED',
          orderDate: '2025-02-14',
          promisedDeliveryDate: '2025-03-10',
          totalAmountINR: 240000,
          currency: 'INR',
          paymentTerms: 'Net 45 Days',
          lineItems: [
            {
              lineId: 'LINE-01',
              skuId: 'SKU-003',
              skuName: '102 Navy-L (Polo)',
              orderedQty: 400,
              receivedQty: 0,
              invoicedQty: 0,
              unitPriceINR: 600,
              totalPriceINR: 240000,
            },
          ],
        },
      ],
      asns: [
        {
          asnNumber: 'ASN-8841',
          poNumber: 'PO-2025-084',
          vendorName: 'Apex Mills & Fabrics Pvt Ltd',
          carrier: 'Gati KWE Express',
          trackingNumber: 'TRK-90214',
          shippedDate: '2025-02-12',
          estimatedArrival: '2025-02-18 (Delayed)',
          itemCount: 2,
          totalUnits: 892,
          status: 'IN_TRANSIT',
        },
        {
          asnNumber: 'ASN-8849',
          poNumber: 'PO-2025-089',
          vendorName: 'Vanguard Knits & Fleece Ltd',
          carrier: 'Delhivery Supply Chain',
          trackingNumber: 'TRK-90215',
          shippedDate: '2025-02-14',
          estimatedArrival: '2025-02-28',
          itemCount: 1,
          totalUnits: 450,
          status: 'DISPATCHED',
        },
        {
          asnNumber: 'ASN-8820',
          poNumber: 'PO-2025-092',
          vendorName: 'DenimCraft Apparel Solutions',
          carrier: 'VRL Logistics',
          trackingNumber: 'TRK-90201',
          shippedDate: '2025-02-08',
          estimatedArrival: '2025-02-14',
          itemCount: 1,
          totalUnits: 370,
          status: 'DELIVERED',
        },
      ],
      matches: [
        {
          matchId: '3WM-8820',
          poNumber: 'PO-2025-092',
          vendorName: 'DenimCraft Apparel Solutions',
          invoiceNumber: 'INV-DC-2025-104',
          poAmountINR: 445000,
          grnAmountINR: 445000,
          invoiceAmountINR: 445000,
          varianceINR: 0,
          status: 'MATCHED',
          auditedTimestamp: '2025-02-14 04:30 PM IST',
        },
        {
          matchId: '3WM-8812',
          poNumber: 'PO-2025-078',
          vendorName: 'Apex Mills & Fabrics Pvt Ltd',
          invoiceNumber: 'INV-AM-2025-881',
          poAmountINR: 250000,
          grnAmountINR: 238000,
          invoiceAmountINR: 250000,
          varianceINR: -12000,
          status: 'DISCREPANCY_QUANTITY',
          auditedTimestamp: '2025-02-11 11:15 AM IST',
          discrepancyNote: 'Short delivery of 28 units recorded at receiving dock. Invoiced for full PO quantity.',
        },
        {
          matchId: '3WM-8841',
          poNumber: 'PO-2025-084',
          vendorName: 'Apex Mills & Fabrics Pvt Ltd',
          invoiceNumber: 'INV-AM-2025-899',
          poAmountINR: 375000,
          grnAmountINR: 0,
          invoiceAmountINR: 375000,
          varianceINR: 0,
          status: 'PENDING_RECEIPT',
          auditedTimestamp: '2025-02-13 09:00 AM IST',
          discrepancyNote: 'Advance invoice received before physical delivery and GRN generation.',
        },
      ],
    };
  }
}