import { QualityAuditReport } from '@/types/quality.types';

export class QualityAdapter {
  /**
   * Normalizes backend quality audit data into structured UI models.
   */
  public static generateSimulatedAudit(): QualityAuditReport {
    return {
      overallScore: 94.2,
      overallHealth: 'OPTIMAL',
      totalRowsAudited: 1480,
      totalColumnsAudited: 8,
      temporalRange: { start: '2024-01-01', end: '2025-01-31' },
      evaluatedAt: new Date().toISOString(),
      dimensions: [
        {
          key: 'completeness',
          name: 'Completeness',
          score: 98.6,
          status: 'optimal',
          description: 'Absence of null or unrecorded observations across critical required fields.',
          affectedRecords: 21,
          totalRecords: 1480,
        },
        {
          key: 'validity',
          name: 'Schema Validity',
          score: 97.4,
          status: 'optimal',
          description: 'Data types, positive integers, and standardized ISO formats verified.',
          affectedRecords: 38,
          totalRecords: 1480,
        },
        {
          key: 'temporal_integrity',
          name: 'Temporal Regularity',
          score: 95.0,
          status: 'optimal',
          description: 'Regular monthly frequency without critical missing intervals.',
          affectedRecords: 0,
          totalRecords: 1480,
        },
        {
          key: 'duplicates',
          name: 'Duplicate Uniqueness',
          score: 100.0,
          status: 'optimal',
          description: 'Zero duplicate primary SKU/Date observation keys found.',
          affectedRecords: 0,
          totalRecords: 1480,
        },
        {
          key: 'sku_integrity',
          name: 'SKU Identifier Consistency',
          score: 92.8,
          status: 'acceptable',
          description: 'Catalog nomenclature matches known enterprise variant taxonomy.',
          affectedRecords: 106,
          totalRecords: 1480,
        },
        {
          key: 'outliers',
          name: 'Extreme Volatility / Outliers',
          score: 86.4,
          status: 'acceptable',
          description: 'Anomalous spikes flagged beyond standard 3-sigma thresholds.',
          affectedRecords: 42,
          totalRecords: 1480,
        },
        {
          key: 'lead_time_integrity',
          name: 'Lead-Time & Receipt Consistency',
          score: 64.0,
          status: 'deficient',
          description: 'Inbound receipt dates missing from batch; historical supply variance is estimated.',
          affectedRecords: 532,
          totalRecords: 1480,
        },
      ],
      readinessMatrix: [
        {
          moduleKey: 'forecasting',
          moduleName: 'Demand & ML Forecasting Engine',
          state: 'READY',
          score: 96.5,
          unmetPrerequisites: [],
          clearanceNote: '13+ consecutive monthly periods verified; eligible for ARIMA, ETS, and XGBoost champion selection.',
        },
        {
          moduleKey: 'inventory',
          moduleName: 'Inventory & Safety Stock Optimization',
          state: 'READY',
          score: 94.0,
          unmetPrerequisites: [],
          clearanceNote: 'Current stock balances and demand variance available for ROP and service-level modeling.',
        },
        {
          moduleKey: 'finance',
          moduleName: 'Working Capital & Economics',
          state: 'READY',
          score: 92.5,
          unmetPrerequisites: [],
          clearanceNote: 'Unit costs mapped; holding cost and stockout financial exposure can be computed.',
        },
        {
          moduleKey: 'supply',
          moduleName: 'Supplier Risk & Lead-Time Analysis',
          state: 'PARTIAL',
          score: 68.0,
          unmetPrerequisites: ['Inbound Purchase Order receipt timestamps missing'],
          clearanceNote: 'Supplier lead-time variance will operate using industry baseline defaults until PO logs are supplied.',
        },
        {
          moduleKey: 'logistics',
          moduleName: 'Logistics & Lane Risk Tracking',
          state: 'PARTIAL',
          score: 71.0,
          unmetPrerequisites: ['GPS / Courier Waybill tracking numbers not supplied'],
          clearanceNote: 'Carrier transit risk is calculated based on historical lane averages rather than live telemetry.',
        },
        {
          moduleKey: 'network',
          moduleName: 'Multi-Echelon Network & Bullwhip',
          state: 'BLOCKED',
          score: 42.0,
          unmetPrerequisites: ['Facility / Node hierarchy codes unmapped', 'Tier-2 distributor orders missing'],
          clearanceNote: 'Requires upstream facility mapping before multi-tier variance propagation can be simulated.',
        },
      ],
      anomalies: [
        {
          id: 'anom-01',
          skuId: '101 Beige-L (T-Shirt)',
          field: 'Outwards_Pcs',
          rowNumber: 14,
          severity: 'warning',
          category: 'outlier',
          valueDetected: 94,
          expectedCondition: 'Historical standard range: [2 - 48] pcs',
          remediationAction: 'Spike detected in Oct 2024. Treated as promotional surge during ARIMA training.',
        },
        {
          id: 'anom-02',
          skuId: '101 Beige-S (T-Shirt)',
          field: 'Cost_Price_INR',
          rowNumber: 62,
          severity: 'critical',
          category: 'negative_value',
          valueDetected: -15,
          expectedCondition: 'Cost price must be positive numerical value (> 0)',
          remediationAction: 'Auto-corrected to mean variant cost price (₹420) during data normalization.',
        },
        {
          id: 'anom-03',
          skuId: '103 Black-XXL (Hoodie)',
          field: 'Period_Date',
          rowNumber: 118,
          severity: 'info',
          category: 'temporal_gap',
          valueDetected: '2024-07-31',
          expectedCondition: 'Consecutive monthly intervals',
          remediationAction: 'Intermittent zero-demand month populated with 0 units without shifting time indices.',
        },
        {
          id: 'anom-04',
          skuId: '104 Olive-M (Jeans)',
          field: 'Supplier_ID',
          rowNumber: 245,
          severity: 'warning',
          category: 'missing_value',
          valueDetected: null,
          expectedCondition: 'Primary supplier identifier assigned',
          remediationAction: 'Fallback to default vendor profile VEND-INTERNAL.',
        },
      ],
    };
  }
}