import { ReturnsReport } from '@/types/returns.types';

export class ReturnsAdapter {
  public static generateSimulatedReturns(): ReturnsReport {
    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        totalReturnsCount: 4,
        totalReturnedUnits: 48,
        aggregateRefundINR: 31200,
        netLossINR: 11400,
        portfolioReturnRatePercent: 3.2,
        topReturnReason: 'SIZE_FIT',
        dispositionMetrics: [
          {
            disposition: 'RESTOCK',
            unitsCount: 32,
            percentageOfTotal: 66.7,
            totalRefundINR: 20800,
            salvageRecoveryINR: 20800,
          },
          {
            disposition: 'REWORK',
            unitsCount: 10,
            percentageOfTotal: 20.8,
            totalRefundINR: 6500,
            salvageRecoveryINR: 4200,
          },
          {
            disposition: 'SCRAP',
            unitsCount: 6,
            percentageOfTotal: 12.5,
            totalRefundINR: 3900,
            salvageRecoveryINR: 0,
          },
        ],
      },
      returns: [
        {
          rmaNumber: 'RMA-2025-041',
          orderId: 'ORD-2025-9812',
          skuId: 'SKU-004',
          skuName: '103 Black-XXL (Hoodie)',
          customerName: 'Rohit Verma (Myntra Customer)',
          returnReason: 'SIZE_FIT',
          disposition: 'RESTOCK',
          returnQty: 1,
          refundAmountINR: 900,
          salvageValueINR: 900,
          netFinancialLossINR: 0,
          requestedDate: '2025-02-12',
          inspectedDate: '2025-02-14',
          inspectionNotes: 'Pristine packaging, brand tags attached. Returned to prime A-grade stock bin.',
        },
        {
          rmaNumber: 'RMA-2025-042',
          orderId: 'ORD-2025-9794',
          skuId: 'SKU-001',
          skuName: '101 Beige-L (T-Shirt)',
          customerName: 'Ananya Sharma (D2C)',
          returnReason: 'FABRIC_DEFECT',
          disposition: 'REWORK',
          returnQty: 12,
          refundAmountINR: 5040,
          salvageValueINR: 3600,
          netFinancialLossINR: 1440,
          requestedDate: '2025-02-10',
          inspectedDate: '2025-02-13',
          inspectionNotes: 'Loose overlock seam on collar rib. Dispatched to Peenya plant rework line for restitching.',
        },
        {
          rmaNumber: 'RMA-2025-043',
          orderId: 'ORD-2025-9750',
          skuId: 'SKU-005',
          skuName: '104 Olive-M (Jeans)',
          customerName: 'Pooja Hegde (Ajio Customer)',
          returnReason: 'SHIPPING_DAMAGE',
          disposition: 'SCRAP',
          returnQty: 5,
          refundAmountINR: 6000,
          salvageValueINR: 0,
          netFinancialLossINR: 6000,
          requestedDate: '2025-02-08',
          inspectedDate: '2025-02-11',
          inspectionNotes: 'Moisture ingress and oil stain sustained during regional courier transit. Scrap write-off.',
        },
        {
          rmaNumber: 'RMA-2025-044',
          orderId: 'ORD-2025-9855',
          skuId: 'SKU-002',
          skuName: '101 Beige-M (T-Shirt)',
          customerName: 'Kunal Kapoor (Lifestyle Retail)',
          returnReason: 'BUYER_REMORSE',
          disposition: 'RESTOCK',
          returnQty: 30,
          refundAmountINR: 12600,
          salvageValueINR: 12600,
          netFinancialLossINR: 0,
          requestedDate: '2025-02-14',
          inspectedDate: '2025-02-14',
          inspectionNotes: 'Unopened master carton returned due to store replenishment floor adjustment. Re-entered inventory.',
        },
      ],
    };
  }
}