import { SalesAnalyticsReport } from '@/types/sales.types';
import { ApiClient } from '@/services/api/apiClient';

export class SalesAdapter {
  public static generateSimulatedSales(): SalesAnalyticsReport {
    const isMock = ApiClient.getMode() === 'MOCK';

    return {
      evaluatedAt: new Date().toISOString(),
      summary: {
        grossRevenueINR: isMock ? 12450000 : 0,
        netRevenueINR: isMock ? 11820000 : 0,
        revenueGrowthPercent: isMock ? 14.8 : 0,
        revenueVsPlanPercent: isMock ? 104.2 : 0,
        totalOrdersCount: isMock ? 342 : 0,
        unitsSold: isMock ? 48500 : 0,
        averageSellingPriceINR: isMock ? 243.6 : 0,
        grossMarginPercent: isMock ? 38.4 : 0,
        contributionMarginPercent: isMock ? 24.2 : 0,
        activeCustomersCount: isMock ? 68 : 0,
        newCustomersCount: isMock ? 9 : 0,
        churnedCustomersCount: isMock ? 2 : 0,
        revenueAtRiskINR: isMock ? 650000 : 0,
        lostSalesValueINR: isMock ? 340000 : 0,
        totalOpportunityValueINR: isMock ? 1850000 : 0,
        evaluatedAt: new Date().toISOString(),
      },
      pvmBreakdown: isMock ? [
        {
          dimension: 'Apparel - T-Shirts (Core Line)',
          baselineRevenueINR: 5000000,
          currentRevenueINR: 5800000,
          netVarianceINR: 800000,
          priceEffectINR: 200000,
          volumeEffectINR: 500000,
          mixEffectINR: 100000,
          contributionPercent: 42.1,
        },
        {
          dimension: 'Apparel - Hoodies & Fleeces',
          baselineRevenueINR: 3500000,
          currentRevenueINR: 4200000,
          netVarianceINR: 700000,
          priceEffectINR: 300000,
          volumeEffectINR: 300000,
          mixEffectINR: 100000,
          contributionPercent: 36.8,
        },
        {
          dimension: 'Accessories & Custom Merch',
          baselineRevenueINR: 1800000,
          currentRevenueINR: 1820000,
          netVarianceINR: 20000,
          priceEffectINR: -50000,
          volumeEffectINR: 80000,
          mixEffectINR: -10000,
          contributionPercent: 1.1,
        },
      ] : [],
      customers: isMock ? [
        {
          customerId: 'CUST-001',
          customerName: 'Apex Retail Chain (South)',
          tier: 'Tier 1 (Enterprise)',
          segment: 'Omnichannel Retail',
          revenueINR: 3450000,
          marginPercent: 34.2,
          ordersCount: 48,
          unitsPurchased: 14500,
          growthPercent: 18.4,
          recencyDays: 2,
          retentionRiskScore: 12.0,
          creditLimitINR: 5000000,
          outstandingBalanceINR: 1250000,
          overdueDaysMax: 0,
          segmentRisk: 'LOW',
        },
        {
          customerId: 'CUST-002',
          customerName: 'Metro Fashion Hubs Pvt Ltd',
          tier: 'Tier 1 (Enterprise)',
          segment: 'Department Stores',
          revenueINR: 2850000,
          marginPercent: 29.8,
          ordersCount: 36,
          unitsPurchased: 11200,
          growthPercent: 8.2,
          recencyDays: 5,
          retentionRiskScore: 28.5,
          creditLimitINR: 4000000,
          outstandingBalanceINR: 2100000,
          overdueDaysMax: 14,
          segmentRisk: 'MODERATE',
        },
        {
          customerId: 'CUST-003',
          customerName: 'Vanguard Apparel Direct',
          tier: 'Tier 2 (Growth)',
          segment: 'D2C E-Commerce',
          revenueINR: 1950000,
          marginPercent: 42.5,
          ordersCount: 84,
          unitsPurchased: 7800,
          growthPercent: 34.2,
          recencyDays: 1,
          retentionRiskScore: 8.0,
          creditLimitINR: 2000000,
          outstandingBalanceINR: 450000,
          overdueDaysMax: 0,
          segmentRisk: 'LOW',
        },
      ] : [],
      concentration: isMock ? [
        { tierName: 'Top 5 Enterprise Accounts', customerCount: 5, revenueINR: 8200000, revenueSharePercent: 65.9, cumulativeSharePercent: 65.9, hhiContribution: 4342 },
        { tierName: 'Mid-Tier Commercial Accounts', customerCount: 22, revenueINR: 3100000, revenueSharePercent: 24.9, cumulativeSharePercent: 90.8, hhiContribution: 620 },
        { tierName: 'Long-Tail Accounts', customerCount: 41, revenueINR: 1150000, revenueSharePercent: 9.2, cumulativeSharePercent: 100.0, hhiContribution: 85 },
      ] : [],
      o2cRisks: isMock ? [
        {
          invoiceId: 'INV-2025-401',
          customerId: 'CUST-002',
          customerName: 'Metro Fashion Hubs Pvt Ltd',
          invoiceAmountINR: 850000,
          dueDate: '2025-02-01',
          daysSalesOutstanding: 58,
          overdueDays: 14,
          riskStatus: 'WATCHLIST',
        },
        {
          invoiceId: 'INV-2025-389',
          customerId: 'CUST-009',
          customerName: 'Legacy Boutique Distributors',
          invoiceAmountINR: 650000,
          dueDate: '2025-01-15',
          daysSalesOutstanding: 74,
          overdueDays: 31,
          riskStatus: 'OVERDUE_CRITICAL',
        },
      ] : [],
      opportunities: isMock ? [
        {
          opportunityId: 'OPP-8801',
          customerId: 'CUST-003',
          customerName: 'Vanguard Apparel Direct',
          opportunityType: 'UPSELL',
          description: 'High sell-through velocity on 180 GSM T-Shirts indicates immediate capacity for Q2 volume expansion (+25%).',
          estimatedValueINR: 750000,
          confidenceScore: 0.89,
          suggestedAction: 'Propose volume rebate tier and lock in Q2 production batch.',
        },
        {
          opportunityId: 'OPP-8802',
          customerId: 'CUST-001',
          customerName: 'Apex Retail Chain (South)',
          opportunityType: 'CROSS_SELL',
          description: 'Expansion into Heavyweight Hoodies line across 40 new retail locations in South zone.',
          estimatedValueINR: 1100000,
          confidenceScore: 0.82,
          suggestedAction: 'Schedule executive product showcase and sample dispatch.',
        },
      ] : [],
    };
  }
}
