"""
AURIX Manufacturing & Production Intelligence — Contracts & Schemas
Phase 23 Core Implementation.
Defines authoritative schemas for Multi-Level BOMs, MRP, Capacity, OEE, Quality,
Downtime, Production Costs, Revenue-at-Risk, and Manufacturing Anomalies.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class DataAvailabilityStatus(str, Enum):
    """Indicator of underlying manufacturing telemetry completeness."""
    AVAILABLE = "AVAILABLE"
    PARTIALLY_AVAILABLE = "PARTIALLY_AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class WorkCenterStatus(str, Enum):
    """Operational status of a machine or work center."""
    OPTIMAL = "OPTIMAL"
    CONSTRAINED = "CONSTRAINED"
    BOTTLENECK = "BOTTLENECK"
    IDLE = "IDLE"
    DOWN = "DOWN"


class ManufacturingAnomalyDomain(str, Enum):
    """Domains for manufacturing process exception detection."""
    SCRAP_SPIKE = "SCRAP_SPIKE"
    YIELD_DROP = "YIELD_DROP"
    UNPLANNED_DOWNTIME = "UNPLANNED_DOWNTIME"
    CYCLE_TIME_DEVIATION = "CYCLE_TIME_DEVIATION"
    MATERIAL_OVERCONSUMPTION = "MATERIAL_OVERCONSUMPTION"
    BOTTLENECK_OVERLOAD = "BOTTLENECK_OVERLOAD"


# --- BOM Schemas ---
class BOMExplodedComponent(BaseModel):
    """Component line resulting from recursive multi-level BOM explosion."""
    component_sku_id: str
    component_name: str
    level: int
    parent_sku_id: str
    quantity_per_parent: float
    scrap_factor: float
    cumulative_multiplier: float
    total_required_quantity: float
    unit_of_measure: str = "PCS"
    lead_time_days: float = 0.0


class BOMExplosionResult(BaseModel):
    """Complete multi-level BOM explosion hierarchy."""
    parent_sku_id: str
    target_production_quantity: float
    max_depth_reached: int
    total_components_count: int
    components: List[BOMExplodedComponent]


# --- MRP Schemas ---
class MRPPlannedOrder(BaseModel):
    """Scheduled purchase or production order recommendation generated by MRP."""
    order_id: str = Field(default_factory=lambda: f"PLN-{uuid.uuid4().hex[:8].upper()}")
    sku_id: str
    order_type: str  # "PURCHASE" or "MANUFACTURE"
    gross_requirement: float
    available_inventory: float
    scheduled_receipts: float
    safety_stock: float
    net_requirement: float
    planned_order_quantity: float
    release_date: datetime
    due_date: datetime
    lead_time_days: float


class MRPRunResult(BaseModel):
    """Consolidated results of a deterministic MRP calculation."""
    run_id: str = Field(default_factory=lambda: f"MRP-{uuid.uuid4().hex[:8].upper()}")
    tenant_id: str
    total_gross_requirement: float
    total_net_requirement: float
    planned_orders: List[MRPPlannedOrder]
    executed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# --- Material Availability Schemas ---
class MaterialAvailabilityItem(BaseModel):
    """Component availability status for production fulfillment."""
    sku_id: str
    sku_name: str
    required_quantity: float
    on_hand_quantity: float
    on_order_quantity: float
    allocated_quantity: float
    net_available_quantity: float
    shortage_quantity: float
    is_critical_shortage: bool
    expected_arrival_date: Optional[datetime] = None


class MaterialAvailabilityReport(BaseModel):
    """Material readiness report for active work orders."""
    tenant_id: str
    work_order_id: Optional[str] = None
    readiness_pct: float
    total_components_checked: int
    shortage_items_count: int
    items: List[MaterialAvailabilityItem]


# --- Capacity & Work Center Schemas ---
class WorkCenterCapacitySummary(BaseModel):
    """Capacity load and utilization analysis for a work center."""
    work_center_id: str
    work_center_name: str
    plant_location_id: str
    available_capacity_hours: float
    required_load_hours: float
    utilization_pct: float
    backlog_hours: float
    status: WorkCenterStatus
    is_bottleneck: bool


# --- OEE Schemas ---
class OEEMetrics(BaseModel):
    """Overall Equipment Effectiveness metrics with explicit data availability guards."""
    work_center_id: str
    period_key: str
    planned_production_time_minutes: float
    actual_run_time_minutes: float
    theoretical_output_units: float
    actual_output_units: float
    good_units: float
    scrap_units: float
    availability_pct: Optional[float] = None
    performance_pct: Optional[float] = None
    quality_pct: Optional[float] = None
    oee_pct: Optional[float] = None
    oee_status: DataAvailabilityStatus
    notes: Optional[str] = None


# --- Quality, Yield & Scrap Schemas ---
class QualityYieldSummary(BaseModel):
    """Production quality, first-pass yield, and scrap loss metrics."""
    tenant_id: str
    period_key: str
    total_units_produced: float
    good_units_produced: float
    scrap_units: float
    rework_units: float
    first_pass_yield_pct: float
    scrap_rate_pct: float
    total_scrap_cost_loss: float
    defect_reasons_breakdown: Dict[str, float] = Field(default_factory=dict)


# --- Downtime Schemas ---
class DowntimeEventSummary(BaseModel):
    """Machine stoppage event breakdown."""
    event_id: str
    work_center_id: str
    machine_id: str
    duration_minutes: float
    reason_code: str
    is_planned: bool
    event_timestamp: datetime


class DowntimeAnalysisReport(BaseModel):
    """Aggregated asset reliability and downtime report."""
    tenant_id: str
    period_key: str
    total_downtime_minutes: float
    unplanned_downtime_minutes: float
    total_stoppages_count: int
    mtbf_hours: float  # Mean Time Between Failures
    mttr_minutes: float  # Mean Time To Repair
    top_downtime_reasons: List[Dict[str, Any]] = Field(default_factory=list)


# --- Production Cost & Revenue-at-Risk ---
class ProductionCostVarianceReport(BaseModel):
    """Actual vs Standard manufacturing cost variance report."""
    tenant_id: str
    period_key: str
    planned_standard_cost: float
    actual_material_cost: float
    actual_labor_cost: float
    actual_scrap_overhead: float
    total_actual_production_cost: float
    cost_variance: float
    cost_variance_pct: float


class ProductionRevenueAtRiskItem(BaseModel):
    """Commercial revenue exposed due to production shortages or delays."""
    work_order_id: str
    sku_id: str
    shortage_quantity: float
    unit_selling_price: float
    revenue_at_risk: float
    customer_id: Optional[str] = None
    promised_delivery_date: Optional[datetime] = None


class ProductionRevenueAtRiskReport(BaseModel):
    """Aggregated financial revenue exposure resulting from manufacturing constraints."""
    tenant_id: str
    period_key: str
    total_revenue_at_risk: float
    impacted_work_orders_count: int
    items: List[ProductionRevenueAtRiskItem]


# --- Anomaly & Summary ---
class ManufacturingAnomalyFinding(BaseModel):
    """Manufacturing process anomaly or outlier alert."""
    anomaly_id: str = Field(default_factory=lambda: f"ANOM-MFG-{uuid.uuid4().hex[:8].upper()}")
    tenant_id: str
    domain: ManufacturingAnomalyDomain
    severity: str = "MEDIUM"
    title: str
    description: str
    detected_metric_value: float
    baseline_expected_value: float
    deviation_pct: float
    entity_id: str
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ManufacturingSummaryReport(BaseModel):
    """Master executive manufacturing & production operating intelligence summary."""
    tenant_id: str
    period_key: str
    total_work_orders: int
    active_work_orders: int
    plant_capacity_utilization_pct: float
    overall_oee_pct: Optional[float] = None
    oee_status: DataAvailabilityStatus
    first_pass_yield_pct: float
    scrap_rate_pct: float
    total_downtime_hours: float
    total_production_revenue_at_risk: float
    bottleneck_work_centers_count: int
    active_anomalies_count: int
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
